/**
 * @file ui_scr_home.h
 * @ingroup ui
 * @brief Home screen object declarations and manually maintained extensions.
 *
 * The bulk of this file is auto-generated by SquareLine Studio and should
 * not be edited manually. The sections marked with "CUSTOM" or by explicit
 * comments below are maintained by hand and document the runtime API used
 * by the rest of the firmware.
 *
 * @note Auto-generated by SquareLine Studio 1.6.0 / LVGL 9.2.2
 *       Project: just-GUI
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_HOME_H
#define UI_SCR_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_home
extern void ui_scr_home_screen_init(void);
extern void ui_scr_home_screen_destroy(void);
extern lv_obj_t * ui_scr_home;
extern lv_obj_t * ui_TabView;
extern lv_obj_t * ui_tabhome;
extern lv_obj_t * ui_panel_left;
extern lv_obj_t * ui_arc_temp;
extern lv_obj_t * ui_lbl_temp_val;
extern lv_obj_t * ui_lbl_temp_unit;
extern lv_obj_t * ui_arc_pressure;
extern lv_obj_t * ui_lbl_press_val;
extern lv_obj_t * ui_lbl_press_unit;
extern lv_obj_t * ui_arc_humidity;
extern lv_obj_t * ui_lbl_hum_val;
extern lv_obj_t * ui_lbl_hum_unit;
extern lv_obj_t * ui_panel_right;
extern lv_obj_t * ui_panel__current_weather;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_lbl_w_temp;
extern lv_obj_t * ui_lbl_w_temp_hi;
extern lv_obj_t * ui_lbl_w_temp_lo;
extern lv_obj_t * ui_lbl_w_desc;
extern lv_obj_t * ui_lbl_w_loc;
extern lv_obj_t * ui_panel_stat_wind;
extern lv_obj_t * ui_labl_stat_wind_;
extern lv_obj_t * ui_labl_stat_wind_val;
extern lv_obj_t * ui_panel_stat_feels;
extern lv_obj_t * ui_labl_stat_feels;
extern lv_obj_t * ui_labl_stat_feels_val;
extern lv_obj_t * ui_panel_stat_sunrise;
extern lv_obj_t * ui_labl_stat_sunrise;
extern lv_obj_t * ui_lbl_stat_sunrise_val;
extern lv_obj_t * ui_panel_stat_sunset;
extern lv_obj_t * ui_labl_stat_sunset;
extern lv_obj_t * ui_lbl_stat_sunset_val;
extern lv_obj_t * ui_panel_elec_rec;
extern lv_obj_t * ui_lbl_elec_status;
extern lv_obj_t * ui_lbl_elec_sub;
extern lv_obj_t * ui_lbl_elec_price;
extern lv_obj_t * ui_tabweather;
extern lv_obj_t * ui_tabelpris;
extern lv_obj_t * ui_tabsettings;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_ta_locationinput;
extern lv_obj_t * ui_dd_price;
extern lv_obj_t * ui_dd_timeout;
extern lv_obj_t * ui_lbl_wifi_name;
extern lv_obj_t * ui_btn_wifi_change;
extern lv_obj_t * ui_dd_timeout;
extern lv_obj_t * ui_panel_statusbar;
extern lv_obj_t * ui_lbl_localtime;
extern lv_obj_t * ui_lbl_wifi_status;
extern lv_obj_t * ui_sw_ap_enabled;
extern lv_obj_t * ui_sw_local_web_client;
extern lv_obj_t * ui_sw_wifi;
extern lv_obj_t * ui_lbl_settings_ip;

/**
 * @name Electricity price traffic-light indicator (Home tab)
 *
 * Three coloured dots that visualise the current electricity price level:
 * - @c ui_dot_light_green  — price is cheap    (≤ CHEAP_MAX öre/kWh)
 * - @c ui_dot_light_amber  — price is moderate (≤ WARN_MAX öre/kWh)
 * - @c ui_dot_light_red    — price is expensive (> WARN_MAX öre/kWh)
 *
 * Thresholds are defined in @c ui_theme.h as @c UI_COLOR_CHEAP_MAX and
 * @c UI_COLOR_WARN_MAX. Only the dot matching the current price level is
 * made fully opaque; the others are dimmed.
 * @{
 */
extern lv_obj_t * ui_panel_traffic_light; /**< Container panel for the three dots. */
extern lv_obj_t * ui_dot_light_green;     /**< Green dot — cheap price indicator. */
extern lv_obj_t * ui_dot_light_amber;     /**< Amber dot — moderate price indicator. */
extern lv_obj_t * ui_dot_light_red;       /**< Red dot — expensive price indicator. */
/** @} */

/**
 * @name Hourly strip — "Next Hours" section (Home tab)
 *
 * Six forecast slots displayed as a horizontal strip at the bottom of the
 * Home tab. Each slot consists of a panel (@c ui_panel_home_hN), a time
 * label (@c ui_lbl_home_htimeN) and a temperature label
 * (@c ui_lbl_home_htempN), where N ranges from 1 to 6.
 * @{
 */
extern lv_obj_t * ui_panel_home_h1;
extern lv_obj_t * ui_lbl_home_htime1;
extern lv_obj_t * ui_lbl_home_htemp1;
extern lv_obj_t * ui_panel_home_h2;
extern lv_obj_t * ui_lbl_home_htime2;
extern lv_obj_t * ui_lbl_home_htemp2;
extern lv_obj_t * ui_panel_home_h3;
extern lv_obj_t * ui_lbl_home_htime3;
extern lv_obj_t * ui_lbl_home_htemp3;
extern lv_obj_t * ui_panel_home_h4;
extern lv_obj_t * ui_lbl_home_htime4;
extern lv_obj_t * ui_lbl_home_htemp4;
extern lv_obj_t * ui_panel_home_h5;
extern lv_obj_t * ui_lbl_home_htime5;
extern lv_obj_t * ui_lbl_home_htemp5;
extern lv_obj_t * ui_panel_home_h6;
extern lv_obj_t * ui_lbl_home_htime6;
extern lv_obj_t * ui_lbl_home_htemp6;
/** @} */

/**
 * @name Tab initialisation and data handlers
 * @{
 */

/** @brief Initialise the Weather tab widgets and layout. */
extern void ui_tab_weather_init(void);

/**
 * @brief Feed a raw weather API JSON response to the Weather tab.
 *
 * Parses the response and updates the 7-day forecast cards,
 * weather icons, current-conditions labels and the hourly strip.
 *
 * @param json  Pointer to a null-terminated JSON string.
 * @param len   Length of @p json in bytes (excluding null terminator).
 */
extern void ui_tab_weather_handle_server_response(const char* json, size_t len);

/** @brief Initialise the Electricity Price (Elpris) tab widgets and layout. */
extern void ui_tab_elpris_init(void);

/**
 * @brief Feed a raw electricity-price API JSON response to the Elpris tab.
 *
 * Parses hourly prices and redraws the price chart.
 *
 * @param json  Pointer to a null-terminated JSON string.
 * @param len   Length of @p json in bytes (excluding null terminator).
 */
extern void ui_tab_elpris_handle_server_response(const char* json, size_t len);

/**
 * @brief Refresh the current-hour highlight on the Elpris tab.
 *
 * Should be called every hour (or after a timezone change) so the chart
 * cursor and recommendation indicator reflect the current time.
 */
extern void ui_tab_elpris_update_now(void);

/** @brief Initialise the Settings tab widgets and layout. */
extern void ui_tab_settings_init(void);

/** @} */

// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_home;
extern lv_obj_t * uic_panel_left;
extern lv_obj_t * uic_arc_temp;
extern lv_obj_t * uic_lbl_temp_val;
extern lv_obj_t * uic_arc_pressure;
extern lv_obj_t * uic_lbl_press_unit;
extern lv_obj_t * uic_arc_humidity;
extern lv_obj_t * uic_lbl_hum_val;
extern lv_obj_t * uic_lbl_hum_unit;
extern lv_obj_t * uic_panel_right;
extern lv_obj_t * uic_panel__current_weather;
extern lv_obj_t * uic_lbl_w_temp_hi;
extern lv_obj_t * uic_lbl_w_temp_lo;
extern lv_obj_t * uic_lbl_w_desc;
extern lv_obj_t * uic_lbl_w_loc;
extern lv_obj_t * uic_panel_stat_wind;
extern lv_obj_t * uic_labl_stat_wind_val;
extern lv_obj_t * uic_panel_stat_feels;
extern lv_obj_t * uic_labl_stat_feels;
extern lv_obj_t * uic_labl_stat_feels_val;
extern lv_obj_t * uic_panel_stat_sunrise;
extern lv_obj_t * uic_labl_stat_sunrise;
extern lv_obj_t * uic_lbl_stat_sunrise_val;
extern lv_obj_t * uic_labl_stat_sunset;
extern lv_obj_t * uic_lbl_stat_sunset_val;
extern lv_obj_t * uic_panel_elec_rec;
extern lv_obj_t * uic_lbl_elec_status;
extern lv_obj_t * uic_lbl_elec_sub;
extern lv_obj_t * uic_lbl_elec_price;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
