// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#include "../images/weather/ui_images_weather.h"
#include "../ui.h"
#include "../ui_theme.h"

// Traffic light dots
lv_obj_t* ui_panel_traffic_light = NULL;
lv_obj_t* ui_dot_light_green     = NULL;
lv_obj_t* ui_dot_light_amber     = NULL;
lv_obj_t* ui_dot_light_red       = NULL;

// Home hourly strip
lv_obj_t* ui_panel_home_h1   = NULL;
lv_obj_t* ui_lbl_home_htime1 = NULL;
lv_obj_t* ui_lbl_home_htemp1 = NULL;
lv_obj_t* ui_panel_home_h2   = NULL;
lv_obj_t* ui_lbl_home_htime2 = NULL;
lv_obj_t* ui_lbl_home_htemp2 = NULL;
lv_obj_t* ui_panel_home_h3   = NULL;
lv_obj_t* ui_lbl_home_htime3 = NULL;
lv_obj_t* ui_lbl_home_htemp3 = NULL;
lv_obj_t* ui_panel_home_h4   = NULL;
lv_obj_t* ui_lbl_home_htime4 = NULL;
lv_obj_t* ui_lbl_home_htemp4 = NULL;
lv_obj_t* ui_panel_home_h5   = NULL;
lv_obj_t* ui_lbl_home_htime5 = NULL;
lv_obj_t* ui_lbl_home_htemp5 = NULL;
lv_obj_t* ui_panel_home_h6   = NULL;
lv_obj_t* ui_lbl_home_htime6 = NULL;
lv_obj_t* ui_lbl_home_htemp6 = NULL;

lv_obj_t* uic_lbl_elec_price;
lv_obj_t* uic_lbl_elec_sub;
lv_obj_t* uic_lbl_elec_status;
lv_obj_t* uic_panel_elec_rec;
lv_obj_t* uic_lbl_stat_sunset_val;
lv_obj_t* uic_labl_stat_sunset;
lv_obj_t* uic_lbl_stat_sunrise_val;
lv_obj_t* uic_labl_stat_sunrise;
lv_obj_t* uic_panel_stat_sunrise;
lv_obj_t* uic_labl_stat_feels_val;
lv_obj_t* uic_labl_stat_feels;
lv_obj_t* uic_panel_stat_feels;
lv_obj_t* uic_labl_stat_wind_val;
lv_obj_t* uic_panel_stat_wind;
lv_obj_t* uic_lbl_w_loc;
lv_obj_t* uic_lbl_w_desc;
lv_obj_t* uic_lbl_w_temp_lo;
lv_obj_t* uic_lbl_w_temp_hi;
lv_obj_t* uic_panel__current_weather;
lv_obj_t* uic_panel_right;
lv_obj_t* uic_lbl_hum_unit;
lv_obj_t* uic_lbl_hum_val;
lv_obj_t* uic_arc_humidity;
lv_obj_t* uic_lbl_press_unit;
lv_obj_t* uic_arc_pressure;
lv_obj_t* uic_lbl_temp_val;
lv_obj_t* uic_arc_temp;
lv_obj_t* uic_panel_left;
lv_obj_t* uic_scr_home;
lv_obj_t* ui_scr_home               = NULL;
lv_obj_t* ui_TabView                = NULL;
lv_obj_t* ui_tabhome                = NULL;
lv_obj_t* ui_panel_left             = NULL;
lv_obj_t* ui_arc_temp               = NULL;
lv_obj_t* ui_lbl_temp_val           = NULL;
lv_obj_t* ui_lbl_temp_unit          = NULL;
lv_obj_t* ui_arc_pressure           = NULL;
lv_obj_t* ui_lbl_press_val          = NULL;
lv_obj_t* ui_lbl_press_unit         = NULL;
lv_obj_t* ui_arc_humidity           = NULL;
lv_obj_t* ui_lbl_hum_val            = NULL;
lv_obj_t* ui_lbl_hum_unit           = NULL;
lv_obj_t* ui_panel_right            = NULL;
lv_obj_t* ui_panel__current_weather = NULL;
lv_obj_t* ui_Image1                 = NULL;
lv_obj_t* ui_lbl_w_temp             = NULL;
lv_obj_t* ui_lbl_w_temp_hi          = NULL;
lv_obj_t* ui_lbl_w_temp_lo          = NULL;
lv_obj_t* ui_lbl_w_desc             = NULL;
lv_obj_t* ui_lbl_w_loc              = NULL;
lv_obj_t* ui_panel_stat_wind        = NULL;
lv_obj_t* ui_labl_stat_wind_        = NULL;
lv_obj_t* ui_labl_stat_wind_val     = NULL;
lv_obj_t* ui_panel_stat_feels       = NULL;
lv_obj_t* ui_labl_stat_feels        = NULL;
lv_obj_t* ui_labl_stat_feels_val    = NULL;
lv_obj_t* ui_panel_stat_sunrise     = NULL;
lv_obj_t* ui_labl_stat_sunrise      = NULL;
lv_obj_t* ui_lbl_stat_sunrise_val   = NULL;
lv_obj_t* ui_panel_stat_sunset      = NULL;
lv_obj_t* ui_labl_stat_sunset       = NULL;
lv_obj_t* ui_lbl_stat_sunset_val    = NULL;
lv_obj_t* ui_panel_elec_rec         = NULL;
lv_obj_t* ui_lbl_elec_status        = NULL;
lv_obj_t* ui_lbl_elec_sub           = NULL;
lv_obj_t* ui_lbl_elec_price         = NULL;
lv_obj_t* ui_tabweather             = NULL;
lv_obj_t* ui_tabelpris              = NULL;
lv_obj_t* ui_tabsettings            = NULL;
lv_obj_t* ui_panel_statusbar        = NULL;
lv_obj_t* ui_lbl_localtime          = NULL;
lv_obj_t* ui_lbl_wifi_status        = NULL;

// build funtions

void ui_scr_home_screen_init(void) {
    ui_scr_home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_home, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_scr_home, UI_COLOR_BG0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView = lv_tabview_create(ui_scr_home);
    lv_obj_remove_flag(lv_tabview_get_content(ui_TabView), LV_OBJ_FLAG_SCROLLABLE);
    lv_tabview_set_tab_bar_size(ui_TabView, 78);
    lv_obj_set_width(ui_TabView, 1024);
    lv_obj_set_height(ui_TabView, 576);
    lv_obj_set_x(ui_TabView, 0);
    lv_obj_set_y(ui_TabView, 24);
    lv_obj_remove_flag(ui_TabView, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_left(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TabView, UI_COLOR_BG0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Tab bar styling
    lv_obj_t* tab_btns = lv_tabview_get_tab_bar(ui_TabView);
    lv_obj_set_style_bg_color(tab_btns, UI_COLOR_BG0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(tab_btns, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(tab_btns, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(tab_btns, UI_COLOR_LINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(tab_btns, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(tab_btns, UI_COLOR_INK3, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(tab_btns, UI_COLOR_BG0, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(tab_btns, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(tab_btns, UI_COLOR_INK1, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(tab_btns, UI_COLOR_BG0, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(tab_btns, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(tab_btns, LV_BORDER_SIDE_BOTTOM, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(tab_btns, UI_COLOR_ACCENT, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(tab_btns, 3, LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_tabhome = lv_tabview_add_tab(ui_TabView, "HOME");
    lv_obj_remove_flag(ui_tabhome, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_left(ui_tabhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tabhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tabhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tabhome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tabhome, UI_COLOR_BG0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── Body: full-size flex-row container ──────────────────────────────────
    lv_obj_t* body = lv_obj_create(ui_tabhome);
    lv_obj_set_size(body, 1024, 498);
    lv_obj_set_pos(body, 0, 0);
    lv_obj_remove_flag(body, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(body, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(body, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(body, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(body, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── LEFT COLUMN ──────────────────────────────────────────────────────────
    ui_panel_left = lv_obj_create(body);
    lv_obj_set_width(ui_panel_left, 488);
    lv_obj_set_height(ui_panel_left, lv_pct(100));
    lv_obj_remove_flag(ui_panel_left, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_panel_left, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_panel_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_panel_left, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(ui_panel_left, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── Indoor sensor card ───────────────────────────────────────────────────
    lv_obj_t* indoor_card = lv_obj_create(ui_panel_left);
    lv_obj_set_width(indoor_card, lv_pct(100));
    lv_obj_set_flex_grow(indoor_card, 1);
    lv_obj_remove_flag(indoor_card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(indoor_card, UI_COLOR_BG1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(indoor_card, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(indoor_card, UI_COLOR_LINE_SOFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(indoor_card, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(indoor_card, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(indoor_card, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(indoor_card, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(indoor_card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* indoor_title = lv_label_create(indoor_card);
    lv_label_set_text(indoor_title, "INDOOR");
    lv_obj_set_style_text_color(indoor_title, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(indoor_title, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(indoor_title, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* gauges_row = lv_obj_create(indoor_card);
    lv_obj_set_width(gauges_row, lv_pct(100));
    lv_obj_set_flex_grow(gauges_row, 1);
    lv_obj_remove_flag(gauges_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(gauges_row, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(gauges_row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(gauges_row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(gauges_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(gauges_row, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);

    // Temperature arc
    ui_arc_temp = lv_arc_create(gauges_row);
    lv_obj_set_size(ui_arc_temp, 130, 130);
    lv_arc_set_rotation(ui_arc_temp, 135);
    lv_arc_set_bg_angles(ui_arc_temp, 0, 270);
    lv_arc_set_range(ui_arc_temp, -40, 85);
    lv_arc_set_value(ui_arc_temp, -40);
    lv_obj_remove_flag(ui_arc_temp, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_arc_color(ui_arc_temp, UI_COLOR_BG3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_temp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_temp, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_temp, UI_COLOR_TEMP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_temp, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_temp, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_temp, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_arc_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_temp_val = lv_label_create(ui_arc_temp);
    lv_label_set_text(ui_lbl_temp_val, "--");
    lv_obj_set_style_text_color(ui_lbl_temp_val, UI_COLOR_TEMP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_temp_val, &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_temp_val, LV_ALIGN_CENTER, 0, -10);

    ui_lbl_temp_unit = lv_label_create(ui_arc_temp);
    lv_label_set_text(ui_lbl_temp_unit, "\xc2\xb0"
                                        "C");
    lv_obj_set_style_text_color(ui_lbl_temp_unit, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_temp_unit, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_temp_unit, LV_ALIGN_CENTER, 0, 18);

    // Humidity arc
    ui_arc_humidity = lv_arc_create(gauges_row);
    lv_obj_set_size(ui_arc_humidity, 130, 130);
    lv_arc_set_rotation(ui_arc_humidity, 135);
    lv_arc_set_bg_angles(ui_arc_humidity, 0, 270);
    lv_arc_set_range(ui_arc_humidity, 0, 100);
    lv_arc_set_value(ui_arc_humidity, 0);
    lv_obj_remove_flag(ui_arc_humidity, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_arc_color(ui_arc_humidity, UI_COLOR_BG3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_humidity, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_humidity, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_humidity, UI_COLOR_HUM, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_humidity, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_humidity, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_humidity, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_arc_humidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hum_val = lv_label_create(ui_arc_humidity);
    lv_label_set_text(ui_lbl_hum_val, "--");
    lv_obj_set_style_text_color(ui_lbl_hum_val, UI_COLOR_HUM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_hum_val, &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_hum_val, LV_ALIGN_CENTER, 0, -10);

    ui_lbl_hum_unit = lv_label_create(ui_arc_humidity);
    lv_label_set_text(ui_lbl_hum_unit, "RH");
    lv_obj_set_style_text_color(ui_lbl_hum_unit, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_hum_unit, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_hum_unit, LV_ALIGN_CENTER, 0, 18);

    // Pressure arc
    ui_arc_pressure = lv_arc_create(gauges_row);
    lv_obj_set_size(ui_arc_pressure, 130, 130);
    lv_arc_set_rotation(ui_arc_pressure, 135);
    lv_arc_set_bg_angles(ui_arc_pressure, 0, 270);
    lv_arc_set_range(ui_arc_pressure, 950, 1050);
    lv_arc_set_value(ui_arc_pressure, 0);
    lv_obj_remove_flag(ui_arc_pressure, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_arc_color(ui_arc_pressure, UI_COLOR_BG3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_pressure, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_pressure, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arc_pressure, UI_COLOR_PRES,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arc_pressure, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arc_pressure, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arc_pressure, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_arc_pressure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_press_val = lv_label_create(ui_arc_pressure);
    lv_label_set_text(ui_lbl_press_val, "--");
    lv_obj_set_style_text_color(ui_lbl_press_val, UI_COLOR_PRES, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_press_val, &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_press_val, LV_ALIGN_CENTER, 0, -10);

    ui_lbl_press_unit = lv_label_create(ui_arc_pressure);
    lv_label_set_text(ui_lbl_press_unit, "hPa");
    lv_obj_set_style_text_color(ui_lbl_press_unit, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_press_unit, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_lbl_press_unit, LV_ALIGN_CENTER, 0, 18);

    // ── Electricity recommendation card ──────────────────────────────────────
    ui_panel_elec_rec = lv_obj_create(ui_panel_left);
    lv_obj_set_width(ui_panel_elec_rec, lv_pct(100));
    lv_obj_set_height(ui_panel_elec_rec, 100);
    lv_obj_remove_flag(ui_panel_elec_rec, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_panel_elec_rec, UI_COLOR_BG1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_elec_rec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_elec_rec, UI_COLOR_LINE_SOFT,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_elec_rec, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_panel_elec_rec, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_panel_elec_rec, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_panel_elec_rec, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_elec_rec, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_panel_elec_rec, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Traffic light dots
    ui_panel_traffic_light = lv_obj_create(ui_panel_elec_rec);
    lv_obj_set_width(ui_panel_traffic_light, 34);
    lv_obj_set_height(ui_panel_traffic_light, lv_pct(100));
    lv_obj_remove_flag(ui_panel_traffic_light, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_panel_traffic_light, UI_COLOR_BG0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_traffic_light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_traffic_light, UI_COLOR_LINE_SOFT,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_traffic_light, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_panel_traffic_light, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_panel_traffic_light, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_panel_traffic_light, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_panel_traffic_light, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);

    ui_dot_light_green = lv_obj_create(ui_panel_traffic_light);
    lv_obj_set_size(ui_dot_light_green, 18, 18);
    lv_obj_set_style_radius(ui_dot_light_green, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot_light_green, UI_COLOR_GOOD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot_light_green, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot_light_green, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dot_light_green, UI_COLOR_GOOD,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dot_light_green, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dot_light_green, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot_light_amber = lv_obj_create(ui_panel_traffic_light);
    lv_obj_set_size(ui_dot_light_amber, 18, 18);
    lv_obj_set_style_radius(ui_dot_light_amber, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot_light_amber, UI_COLOR_WARN, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot_light_amber, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot_light_amber, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot_light_red = lv_obj_create(ui_panel_traffic_light);
    lv_obj_set_size(ui_dot_light_red, 18, 18);
    lv_obj_set_style_radius(ui_dot_light_red, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot_light_red, UI_COLOR_BAD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot_light_red, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot_light_red, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Text column
    lv_obj_t* elec_text_col = lv_obj_create(ui_panel_elec_rec);
    lv_obj_set_flex_grow(elec_text_col, 1);
    lv_obj_set_height(elec_text_col, lv_pct(100));
    lv_obj_remove_flag(elec_text_col, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(elec_text_col, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(elec_text_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(elec_text_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(elec_text_col, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(elec_text_col, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(elec_text_col, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_elec_status = lv_label_create(elec_text_col);
    lv_label_set_text(ui_lbl_elec_status, "--");
    lv_obj_set_width(ui_lbl_elec_status, lv_pct(100));
    lv_obj_set_style_text_color(ui_lbl_elec_status, UI_COLOR_GOOD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_elec_status, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_elec_sub = lv_label_create(elec_text_col);
    lv_label_set_text(ui_lbl_elec_sub, "--");
    lv_obj_set_width(ui_lbl_elec_sub, lv_pct(100));
    lv_obj_set_style_text_color(ui_lbl_elec_sub, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_elec_sub, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    // Price column
    lv_obj_t* elec_price_col = lv_obj_create(ui_panel_elec_rec);
    lv_obj_set_width(elec_price_col, 90);
    lv_obj_set_height(elec_price_col, lv_pct(100));
    lv_obj_remove_flag(elec_price_col, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(elec_price_col, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(elec_price_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(elec_price_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(elec_price_col, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(elec_price_col, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END,
                          LV_FLEX_ALIGN_END);
    lv_obj_set_style_pad_row(elec_price_col, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_elec_price = lv_label_create(elec_price_col);
    lv_label_set_text(ui_lbl_elec_price, "--");
    lv_obj_set_style_text_color(ui_lbl_elec_price, UI_COLOR_GOOD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_elec_price, &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* elec_unit = lv_label_create(elec_price_col);
    lv_label_set_text(elec_unit, "kr/kWh");
    lv_obj_set_style_text_color(elec_unit, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(elec_unit, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── RIGHT COLUMN (weather card) ───────────────────────────────────────────
    ui_panel_right = lv_obj_create(body);
    lv_obj_set_flex_grow(ui_panel_right, 1);
    lv_obj_set_height(ui_panel_right, lv_pct(100));
    lv_obj_remove_flag(ui_panel_right, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_panel_right, UI_COLOR_BG1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_right, UI_COLOR_LINE_SOFT,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_right, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_panel_right, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_panel_right, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_panel_right, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(ui_panel_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* outdoor_title = lv_label_create(ui_panel_right);
    lv_label_set_text(outdoor_title, "OUTDOOR | ");
    lv_obj_set_style_text_color(outdoor_title, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(outdoor_title, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(outdoor_title, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Current weather row
    ui_panel__current_weather = lv_obj_create(ui_panel_right);
    lv_obj_set_width(ui_panel__current_weather, lv_pct(100));
    lv_obj_set_height(ui_panel__current_weather, LV_SIZE_CONTENT);
    lv_obj_remove_flag(ui_panel__current_weather, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_panel__current_weather, LV_OPA_TRANSP,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel__current_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_panel__current_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_panel__current_weather, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel__current_weather, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_panel__current_weather, 18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Current weather icon
    ui_Image1 = lv_image_create(ui_panel__current_weather);
    lv_image_set_src(ui_Image1, &UI_IMG_WX_PARTLY_PNG);
    lv_obj_set_size(ui_Image1, 64, 64);

    // Weather info column
    lv_obj_t* wx_info_col = lv_obj_create(ui_panel__current_weather);
    lv_obj_set_flex_grow(wx_info_col, 1);
    lv_obj_set_height(wx_info_col, LV_SIZE_CONTENT);
    lv_obj_remove_flag(wx_info_col, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(wx_info_col, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(wx_info_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(wx_info_col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(wx_info_col, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(wx_info_col, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_w_temp = lv_label_create(wx_info_col);
    lv_label_set_text(ui_lbl_w_temp, "--");
    lv_obj_set_style_text_color(ui_lbl_w_temp, UI_COLOR_INK1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_w_temp, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_w_desc = lv_label_create(wx_info_col);
    lv_label_set_text(ui_lbl_w_desc, "--");
    lv_obj_set_style_text_color(ui_lbl_w_desc, UI_COLOR_INK1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_w_desc, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_w_loc = lv_label_create(wx_info_col);
    lv_label_set_text(ui_lbl_w_loc, "--");
    lv_obj_set_style_text_color(ui_lbl_w_loc, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_w_loc, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* extremes_row = lv_obj_create(wx_info_col);
    lv_obj_set_width(extremes_row, LV_SIZE_CONTENT);
    lv_obj_set_height(extremes_row, LV_SIZE_CONTENT);
    lv_obj_remove_flag(extremes_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(extremes_row, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(extremes_row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(extremes_row, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(extremes_row, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(extremes_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(extremes_row, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_w_temp_hi = lv_label_create(extremes_row);
    lv_label_set_text(ui_lbl_w_temp_hi, "Hi --");
    lv_obj_set_style_text_color(ui_lbl_w_temp_hi, UI_COLOR_BAD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_w_temp_hi, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_w_temp_lo = lv_label_create(extremes_row);
    lv_label_set_text(ui_lbl_w_temp_lo, "Lo --");
    lv_obj_set_style_text_color(ui_lbl_w_temp_lo, UI_COLOR_HUM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_w_temp_lo, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    // ── Stat boxes (2 rows × 2 cols) ─────────────────────────────────────────
    lv_obj_t* stats_block = lv_obj_create(ui_panel_right);
    lv_obj_set_width(stats_block, lv_pct(100));
    lv_obj_set_height(stats_block, LV_SIZE_CONTENT);
    lv_obj_remove_flag(stats_block, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(stats_block, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(stats_block, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(stats_block, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(stats_block, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(stats_block, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(stats_block, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* stats_row1 = lv_obj_create(stats_block);
    lv_obj_set_width(stats_row1, lv_pct(100));
    lv_obj_set_height(stats_row1, 60);
    lv_obj_remove_flag(stats_row1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(stats_row1, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(stats_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(stats_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(stats_row1, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(stats_row1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* stats_row2 = lv_obj_create(stats_block);
    lv_obj_set_width(stats_row2, lv_pct(100));
    lv_obj_set_height(stats_row2, 60);
    lv_obj_remove_flag(stats_row2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(stats_row2, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(stats_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(stats_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(stats_row2, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(stats_row2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

#define MAKE_STAT_BOX(parent, box_var, lbl_title_var, lbl_val_var, title_txt, val_txt)             \
    box_var = lv_obj_create(parent);                                                               \
    lv_obj_set_flex_grow(box_var, 1);                                                              \
    lv_obj_set_height(box_var, 60);                                                                \
    lv_obj_remove_flag(box_var, LV_OBJ_FLAG_SCROLLABLE);                                           \
    lv_obj_set_style_bg_color(box_var, UI_COLOR_BG2, LV_PART_MAIN | LV_STATE_DEFAULT);             \
    lv_obj_set_style_bg_opa(box_var, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        \
    lv_obj_set_style_border_color(box_var, UI_COLOR_LINE_SOFT, LV_PART_MAIN | LV_STATE_DEFAULT);   \
    lv_obj_set_style_border_width(box_var, 1, LV_PART_MAIN | LV_STATE_DEFAULT);                    \
    lv_obj_set_style_radius(box_var, 10, LV_PART_MAIN | LV_STATE_DEFAULT);                         \
    lv_obj_set_style_pad_hor(box_var, 12, LV_PART_MAIN | LV_STATE_DEFAULT);                        \
    lv_obj_set_style_pad_ver(box_var, 10, LV_PART_MAIN | LV_STATE_DEFAULT);                        \
    lbl_title_var = lv_label_create(box_var);                                                      \
    lv_label_set_text(lbl_title_var, title_txt);                                                   \
    lv_obj_set_style_text_color(lbl_title_var, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);    \
    lv_obj_set_style_text_font(lbl_title_var, &lv_font_montserrat_12,                              \
                               LV_PART_MAIN | LV_STATE_DEFAULT);                                   \
    lv_obj_align(lbl_title_var, LV_ALIGN_TOP_LEFT, 0, 0);                                          \
    lbl_val_var = lv_label_create(box_var);                                                        \
    lv_label_set_text(lbl_val_var, val_txt);                                                       \
    lv_obj_set_style_text_color(lbl_val_var, UI_COLOR_INK1, LV_PART_MAIN | LV_STATE_DEFAULT);      \
    lv_obj_set_style_text_font(lbl_val_var, &lv_font_montserrat_16,                                \
                               LV_PART_MAIN | LV_STATE_DEFAULT);                                   \
    lv_obj_align(lbl_val_var, LV_ALIGN_BOTTOM_LEFT, 0, 0);

    MAKE_STAT_BOX(stats_row1, ui_panel_stat_wind, ui_labl_stat_wind_, ui_labl_stat_wind_val, "WIND",
                  "--")
    MAKE_STAT_BOX(stats_row1, ui_panel_stat_feels, ui_labl_stat_feels, ui_labl_stat_feels_val,
                  "FEELS LIKE", "--")
    MAKE_STAT_BOX(stats_row2, ui_panel_stat_sunrise, ui_labl_stat_sunrise, ui_lbl_stat_sunrise_val,
                  "SUNRISE", "--")
    MAKE_STAT_BOX(stats_row2, ui_panel_stat_sunset, ui_labl_stat_sunset, ui_lbl_stat_sunset_val,
                  "SUNSET", "--")

    // ── Hourly strip (fills remaining space) ─────────────────────────────────
    lv_obj_t* hourly_section = lv_obj_create(ui_panel_right);
    lv_obj_set_width(hourly_section, lv_pct(100));
    lv_obj_set_flex_grow(hourly_section, 1);
    lv_obj_remove_flag(hourly_section, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(hourly_section, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(hourly_section, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(hourly_section, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(hourly_section, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(hourly_section, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(hourly_section, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(hourly_section, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* lbl_next_hours = lv_label_create(hourly_section);
    lv_label_set_text(lbl_next_hours, "NEXT HOURS");
    lv_obj_set_style_text_color(lbl_next_hours, UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lbl_next_hours, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* hourly_strip = lv_obj_create(hourly_section);
    lv_obj_set_width(hourly_strip, lv_pct(100));
    lv_obj_set_height(hourly_strip, 88);
    lv_obj_remove_flag(hourly_strip, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(hourly_strip, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(hourly_strip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(hourly_strip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(hourly_strip, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(hourly_strip, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    static const char* hour_times[] = {"--", "--", "--", "--", "--", "--"};
    static const char* hour_temps[] = {"--", "--", "--", "--", "--", "--"};
    lv_obj_t** cell_panels[]        = {&ui_panel_home_h1, &ui_panel_home_h2, &ui_panel_home_h3,
                                       &ui_panel_home_h4, &ui_panel_home_h5, &ui_panel_home_h6};
    lv_obj_t** cell_times[] = {&ui_lbl_home_htime1, &ui_lbl_home_htime2, &ui_lbl_home_htime3,
                               &ui_lbl_home_htime4, &ui_lbl_home_htime5, &ui_lbl_home_htime6};
    lv_obj_t** cell_temps[] = {&ui_lbl_home_htemp1, &ui_lbl_home_htemp2, &ui_lbl_home_htemp3,
                               &ui_lbl_home_htemp4, &ui_lbl_home_htemp5, &ui_lbl_home_htemp6};
    const lv_image_dsc_t* hour_icons[] = {
        &UI_IMG_WX_SUNNY_PNG,  &UI_IMG_WX_PARTLY_PNG,       &UI_IMG_WX_PARTLY_PNG,
        &UI_IMG_WX_CLOUDY_PNG, &UI_IMG_WMO_RAIN_SLIGHT_PNG, &UI_IMG_WX_RAIN_PNG,
    };

    for (int i = 0; i < 6; i++) {
        *cell_panels[i] = lv_obj_create(hourly_strip);
        lv_obj_set_flex_grow(*cell_panels[i], 1);
        lv_obj_set_height(*cell_panels[i], 88);
        lv_obj_remove_flag(*cell_panels[i], LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(*cell_panels[i], UI_COLOR_BG2, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(*cell_panels[i], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(*cell_panels[i], UI_COLOR_LINE_SOFT,
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(*cell_panels[i], 1, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(*cell_panels[i], 8, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_all(*cell_panels[i], 6, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_flex_flow(*cell_panels[i], LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(*cell_panels[i], LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                              LV_FLEX_ALIGN_CENTER);

        *cell_times[i] = lv_label_create(*cell_panels[i]);
        lv_label_set_text(*cell_times[i], hour_times[i]);
        lv_obj_set_style_text_color(*cell_times[i], UI_COLOR_INK3, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(*cell_times[i], &lv_font_montserrat_12,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_t* h_icon = lv_image_create(*cell_panels[i]);
        lv_image_set_src(h_icon, hour_icons[i]);
        lv_image_set_scale(h_icon, 128);
        lv_obj_set_size(h_icon, 32, 32);

        *cell_temps[i] = lv_label_create(*cell_panels[i]);
        lv_label_set_text(*cell_temps[i], hour_temps[i]);
        lv_obj_set_style_text_color(*cell_temps[i], UI_COLOR_INK1, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(*cell_temps[i], &lv_font_montserrat_14,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    ui_tabweather = lv_tabview_add_tab(ui_TabView, "WEATHER");
    lv_obj_set_style_pad_left(ui_tabweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tabweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tabweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tabweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tab_weather_init();

    ui_tabelpris = lv_tabview_add_tab(ui_TabView, "ELPRIS");
    lv_obj_set_style_pad_left(ui_tabelpris, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tabelpris, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tabelpris, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tabelpris, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_tab_elpris_init();

    ui_tabsettings = lv_tabview_add_tab(ui_TabView, "SETTINGS");
    lv_obj_set_style_pad_left(ui_tabsettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tabsettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tabsettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tabsettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_tab_settings_init();

    ui_panel_statusbar = lv_obj_create(ui_scr_home);
    lv_obj_set_width(ui_panel_statusbar, 1024);
    lv_obj_set_height(ui_panel_statusbar, 24);
    lv_obj_remove_flag(ui_panel_statusbar, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_statusbar, UI_COLOR_BG0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_statusbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_localtime = lv_label_create(ui_panel_statusbar);
    lv_obj_set_width(ui_lbl_localtime, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_height(ui_lbl_localtime, LV_SIZE_CONTENT); /// 20
    lv_obj_align(ui_lbl_localtime, LV_ALIGN_RIGHT_MID, -8, 0);
    lv_label_set_text(ui_lbl_localtime, "--");

    ui_lbl_wifi_status = lv_label_create(ui_panel_statusbar);
    lv_obj_set_width(ui_lbl_wifi_status, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_height(ui_lbl_wifi_status, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_wifi_status, 12);
    lv_obj_set_y(ui_lbl_wifi_status, 5);
    lv_label_set_long_mode(ui_lbl_wifi_status, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lbl_wifi_status, "WIFI");

    uic_scr_home               = ui_scr_home;
    uic_panel_left             = ui_panel_left;
    uic_arc_temp               = ui_arc_temp;
    uic_lbl_temp_val           = ui_lbl_temp_val;
    uic_arc_pressure           = ui_arc_pressure;
    uic_lbl_press_unit         = ui_lbl_press_unit;
    uic_arc_humidity           = ui_arc_humidity;
    uic_lbl_hum_val            = ui_lbl_hum_val;
    uic_lbl_hum_unit           = ui_lbl_hum_unit;
    uic_panel_right            = ui_panel_right;
    uic_panel__current_weather = ui_panel__current_weather;
    uic_lbl_w_temp_hi          = ui_lbl_w_temp_hi;
    uic_lbl_w_temp_lo          = ui_lbl_w_temp_lo;
    uic_lbl_w_desc             = ui_lbl_w_desc;
    uic_lbl_w_loc              = ui_lbl_w_loc;
    uic_panel_stat_wind        = ui_panel_stat_wind;
    uic_labl_stat_wind_val     = ui_labl_stat_wind_val;
    uic_panel_stat_feels       = ui_panel_stat_feels;
    uic_labl_stat_feels        = ui_labl_stat_feels;
    uic_labl_stat_feels_val    = ui_labl_stat_feels_val;
    uic_panel_stat_sunrise     = ui_panel_stat_sunrise;
    uic_labl_stat_sunrise      = ui_labl_stat_sunrise;
    uic_lbl_stat_sunrise_val   = ui_lbl_stat_sunrise_val;
    uic_labl_stat_sunset       = ui_labl_stat_sunset;
    uic_lbl_stat_sunset_val    = ui_lbl_stat_sunset_val;
    uic_panel_elec_rec         = ui_panel_elec_rec;
    uic_lbl_elec_status        = ui_lbl_elec_status;
    uic_lbl_elec_sub           = ui_lbl_elec_sub;
    uic_lbl_elec_price         = ui_lbl_elec_price;
}

void ui_scr_home_screen_destroy(void) {
    if (ui_scr_home) {
        lv_obj_del(ui_scr_home);
    }

    // NULL screen variables
    uic_scr_home               = NULL;
    ui_scr_home                = NULL;
    ui_TabView                 = NULL;
    ui_tabhome                 = NULL;
    uic_panel_left             = NULL;
    ui_panel_left              = NULL;
    uic_arc_temp               = NULL;
    ui_arc_temp                = NULL;
    uic_lbl_temp_val           = NULL;
    ui_lbl_temp_val            = NULL;
    ui_lbl_temp_unit           = NULL;
    uic_arc_pressure           = NULL;
    ui_arc_pressure            = NULL;
    ui_lbl_press_val           = NULL;
    uic_lbl_press_unit         = NULL;
    ui_lbl_press_unit          = NULL;
    uic_arc_humidity           = NULL;
    ui_arc_humidity            = NULL;
    uic_lbl_hum_val            = NULL;
    ui_lbl_hum_val             = NULL;
    uic_lbl_hum_unit           = NULL;
    ui_lbl_hum_unit            = NULL;
    uic_panel_right            = NULL;
    ui_panel_right             = NULL;
    uic_panel__current_weather = NULL;
    ui_panel__current_weather  = NULL;
    ui_Image1                  = NULL;
    ui_lbl_w_temp              = NULL;
    uic_lbl_w_temp_hi          = NULL;
    ui_lbl_w_temp_hi           = NULL;
    uic_lbl_w_temp_lo          = NULL;
    ui_lbl_w_temp_lo           = NULL;
    uic_lbl_w_desc             = NULL;
    ui_lbl_w_desc              = NULL;
    uic_lbl_w_loc              = NULL;
    ui_lbl_w_loc               = NULL;
    uic_panel_stat_wind        = NULL;
    ui_panel_stat_wind         = NULL;
    ui_labl_stat_wind_         = NULL;
    uic_labl_stat_wind_val     = NULL;
    ui_labl_stat_wind_val      = NULL;
    uic_panel_stat_feels       = NULL;
    ui_panel_stat_feels        = NULL;
    uic_labl_stat_feels        = NULL;
    ui_labl_stat_feels         = NULL;
    uic_labl_stat_feels_val    = NULL;
    ui_labl_stat_feels_val     = NULL;
    uic_panel_stat_sunrise     = NULL;
    ui_panel_stat_sunrise      = NULL;
    uic_labl_stat_sunrise      = NULL;
    ui_labl_stat_sunrise       = NULL;
    uic_lbl_stat_sunrise_val   = NULL;
    ui_lbl_stat_sunrise_val    = NULL;
    ui_panel_stat_sunset       = NULL;
    uic_labl_stat_sunset       = NULL;
    ui_labl_stat_sunset        = NULL;
    uic_lbl_stat_sunset_val    = NULL;
    ui_lbl_stat_sunset_val     = NULL;
    uic_panel_elec_rec         = NULL;
    ui_panel_elec_rec          = NULL;
    uic_lbl_elec_status        = NULL;
    ui_lbl_elec_status         = NULL;
    uic_lbl_elec_sub           = NULL;
    ui_lbl_elec_sub            = NULL;
    uic_lbl_elec_price         = NULL;
    ui_lbl_elec_price          = NULL;
    ui_tabweather              = NULL;
    ui_tabelpris               = NULL;
    ui_tabsettings             = NULL;
    ui_panel_statusbar         = NULL;
    ui_lbl_localtime           = NULL;
    ui_lbl_wifi_status         = NULL;
}
