// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#include "../ui.h"

lv_obj_t * uic_img_hour_icon1;
lv_obj_t * uic_lbl_hour_precip1;
lv_obj_t * uic_lbl_hour_temp1;
lv_obj_t * uic_lbl_hour_time1;
lv_obj_t * uic_panel_hour1;
lv_obj_t * uic_panel_hours;
lv_obj_t * uic_lbl_detail_lo;
lv_obj_t * uic_lbl_detail_hi;
lv_obj_t * uic_lbl_detail_desc;
lv_obj_t * uic_lbl_datail_name;
lv_obj_t * uic_panel_detail;
lv_obj_t * uic_lbl_day_lo;
lv_obj_t * uic_lbl_day_hi;
lv_obj_t * uic_img_day_icon;
lv_obj_t * uic_lbl_day_name;
lv_obj_t * uic_panel_carousel;
lv_obj_t * uic_scr_weather;
lv_obj_t * ui_scr_weather = NULL;
lv_obj_t * ui_panel_navbar1 = NULL;
lv_obj_t * ui_btn_home2 = NULL;
lv_obj_t * ui_lbl_navabar_home2 = NULL;
lv_obj_t * ui_btn__weather2 = NULL;
lv_obj_t * ui_lbl_navabar_weather2 = NULL;
lv_obj_t * ui_btn_elpris2 = NULL;
lv_obj_t * ui_lbl_navabar_elpris2 = NULL;
lv_obj_t * ui_btn_settings2 = NULL;
lv_obj_t * ui_lbl_navabar_settings2 = NULL;
lv_obj_t * ui_panel_status2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_panel_carousel = NULL;
lv_obj_t * ui_btn_day1 = NULL;
lv_obj_t * ui_lbl_day_name = NULL;
lv_obj_t * ui_img_day_icon = NULL;
lv_obj_t * ui_lbl_day_hi = NULL;
lv_obj_t * ui_lbl_day_lo = NULL;
lv_obj_t * ui_btn_day2 = NULL;
lv_obj_t * ui_lbl_day_name1 = NULL;
lv_obj_t * ui_img_day_icon1 = NULL;
lv_obj_t * ui_lbl_day_hi1 = NULL;
lv_obj_t * ui_lbl_day_lo1 = NULL;
lv_obj_t * ui_btn_day3 = NULL;
lv_obj_t * ui_lbl_day_name2 = NULL;
lv_obj_t * ui_img_day_icon2 = NULL;
lv_obj_t * ui_lbl_day_hi2 = NULL;
lv_obj_t * ui_lbl_day_lo2 = NULL;
lv_obj_t * ui_btn_day4 = NULL;
lv_obj_t * ui_lbl_day_name3 = NULL;
lv_obj_t * ui_img_day_icon3 = NULL;
lv_obj_t * ui_lbl_day_hi3 = NULL;
lv_obj_t * ui_lbl_day_lo3 = NULL;
lv_obj_t * ui_btn_day5 = NULL;
lv_obj_t * ui_lbl_day_name4 = NULL;
lv_obj_t * ui_img_day_icon4 = NULL;
lv_obj_t * ui_lbl_day_hi4 = NULL;
lv_obj_t * ui_lbl_day_lo4 = NULL;
lv_obj_t * ui_btn_day6 = NULL;
lv_obj_t * ui_lbl_day_name5 = NULL;
lv_obj_t * ui_img_day_icon5 = NULL;
lv_obj_t * ui_lbl_day_hi5 = NULL;
lv_obj_t * ui_lbl_day_lo5 = NULL;
lv_obj_t * ui_btn_day7 = NULL;
lv_obj_t * ui_lbl_day_name6 = NULL;
lv_obj_t * ui_img_day_icon6 = NULL;
lv_obj_t * ui_lbl_day_hi6 = NULL;
lv_obj_t * ui_lbl_day_lo6 = NULL;
lv_obj_t * ui_panel_detail = NULL;
lv_obj_t * ui_lbl_detail_name = NULL;
lv_obj_t * ui_lbl_detail_desc = NULL;
lv_obj_t * ui_lbl_detail_hi = NULL;
lv_obj_t * ui_lbl_detail_lo = NULL;
lv_obj_t * ui_panel_hours = NULL;
lv_obj_t * ui_panel_hour1 = NULL;
lv_obj_t * ui_lbl_hour_time1 = NULL;
lv_obj_t * ui_lbl_hour_temp1 = NULL;
lv_obj_t * ui_lbl_hour_precip1 = NULL;
lv_obj_t * ui_img_hour_icon1 = NULL;
lv_obj_t * ui_panel_hour2 = NULL;
lv_obj_t * ui_lbl_hour_time2 = NULL;
lv_obj_t * ui_lbl_hour_temp2 = NULL;
lv_obj_t * ui_lbl_hour_precip2 = NULL;
lv_obj_t * ui_img_hour_icon2 = NULL;
lv_obj_t * ui_panel_hour3 = NULL;
lv_obj_t * ui_lbl_hour_time3 = NULL;
lv_obj_t * ui_lbl_hour_temp3 = NULL;
lv_obj_t * ui_lbl_hour_precip3 = NULL;
lv_obj_t * ui_img_hour_icon3 = NULL;
lv_obj_t * ui_panel_hour4 = NULL;
lv_obj_t * ui_lbl_hour_time4 = NULL;
lv_obj_t * ui_lbl_hour_temp4 = NULL;
lv_obj_t * ui_lbl_hour_precip4 = NULL;
lv_obj_t * ui_img_hour_icon4 = NULL;
lv_obj_t * ui_panel_hour5 = NULL;
lv_obj_t * ui_lbl_hour_time5 = NULL;
lv_obj_t * ui_lbl_hour_temp5 = NULL;
lv_obj_t * ui_lbl_hour_precip5 = NULL;
lv_obj_t * ui_img_hour_icon5 = NULL;
lv_obj_t * ui_panel_hour6 = NULL;
lv_obj_t * ui_lbl_hour_time6 = NULL;
lv_obj_t * ui_lbl_hour_temp6 = NULL;
lv_obj_t * ui_lbl_hour_precip6 = NULL;
lv_obj_t * ui_img_hour_icon6 = NULL;
lv_obj_t * ui_panel_hour7 = NULL;
lv_obj_t * ui_lbl_hour_time7 = NULL;
lv_obj_t * ui_lbl_hour_temp7 = NULL;
lv_obj_t * ui_lbl_hour_precip7 = NULL;
lv_obj_t * ui_img_hour_icon7 = NULL;
lv_obj_t * ui_panel_hour8 = NULL;
lv_obj_t * ui_lbl_hour_time8 = NULL;
lv_obj_t * ui_lbl_hour_temp8 = NULL;
lv_obj_t * ui_lbl_hour_precip8 = NULL;
lv_obj_t * ui_img_hour_icon8 = NULL;
lv_obj_t * ui_panel_hour9 = NULL;
lv_obj_t * ui_lbl_hour_time9 = NULL;
lv_obj_t * ui_lbl_hour_temp9 = NULL;
lv_obj_t * ui_lbl_hour_precip9 = NULL;
lv_obj_t * ui_img_hour_icon9 = NULL;
// event funtions

// build funtions

void ui_scr_weather_screen_init(void)
{
    ui_scr_weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scr_weather, lv_color_hex(0x252535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_navbar1 = lv_obj_create(ui_scr_weather);
    lv_obj_set_width(ui_panel_navbar1, 1024);
    lv_obj_set_height(ui_panel_navbar1, 78);
    lv_obj_set_x(ui_panel_navbar1, 0);
    lv_obj_set_y(ui_panel_navbar1, -1);
    lv_obj_set_flex_flow(ui_panel_navbar1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_navbar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_panel_navbar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_navbar1, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_navbar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_navbar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_navbar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_navbar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_navbar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_navbar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_navbar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_home2 = lv_button_create(ui_panel_navbar1);
    lv_obj_set_width(ui_btn_home2, 230);
    lv_obj_set_height(ui_btn_home2, 78);
    lv_obj_set_x(ui_btn_home2, 289);
    lv_obj_set_y(ui_btn_home2, -28);
    lv_obj_add_flag(ui_btn_home2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn_home2, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_home2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_home2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_home2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_home2, lv_color_hex(0xA0A0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_home2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_home2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_home2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_btn_home2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_btn_home2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_home2 = lv_label_create(ui_btn_home2);
    lv_obj_set_width(ui_lbl_navabar_home2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_navabar_home2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_navabar_home2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_home2, "HOME");

    ui_btn__weather2 = lv_button_create(ui_panel_navbar1);
    lv_obj_set_width(ui_btn__weather2, 230);
    lv_obj_set_height(ui_btn__weather2, 78);
    lv_obj_add_flag(ui_btn__weather2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn__weather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn__weather2, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn__weather2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn__weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn__weather2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn__weather2, lv_color_hex(0xA0A0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn__weather2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn__weather2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn__weather2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_weather2 = lv_label_create(ui_btn__weather2);
    lv_obj_set_width(ui_lbl_navabar_weather2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_navabar_weather2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_navabar_weather2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_weather2, "WEATEHER");

    ui_btn_elpris2 = lv_button_create(ui_panel_navbar1);
    lv_obj_set_width(ui_btn_elpris2, 230);
    lv_obj_set_height(ui_btn_elpris2, 78);
    lv_obj_add_flag(ui_btn_elpris2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_elpris2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn_elpris2, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_elpris2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_elpris2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_elpris2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_elpris2, lv_color_hex(0xA0A0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_elpris2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_elpris2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_elpris2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_elpris2 = lv_label_create(ui_btn_elpris2);
    lv_obj_set_width(ui_lbl_navabar_elpris2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_navabar_elpris2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_navabar_elpris2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_elpris2, "ELPRIS");

    ui_btn_settings2 = lv_button_create(ui_panel_navbar1);
    lv_obj_set_width(ui_btn_settings2, 230);
    lv_obj_set_height(ui_btn_settings2, 78);
    lv_obj_add_flag(ui_btn_settings2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_settings2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn_settings2, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_settings2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_settings2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_settings2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_settings2, lv_color_hex(0xA0A0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_settings2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_settings2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_settings2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_settings2 = lv_label_create(ui_btn_settings2);
    lv_obj_set_width(ui_lbl_navabar_settings2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_navabar_settings2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbl_navabar_settings2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_settings2, "SETTINGS");

    ui_panel_status2 = lv_obj_create(ui_panel_navbar1);
    lv_obj_set_width(ui_panel_status2, 104);
    lv_obj_set_height(ui_panel_status2, 78);
    lv_obj_set_align(ui_panel_status2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel_status2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_status2, lv_color_hex(0x202439), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_status2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_status2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_panel_status2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "$EF WiFi");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_carousel = lv_obj_create(ui_scr_weather);
    lv_obj_set_width(ui_panel_carousel, 1024);
    lv_obj_set_height(ui_panel_carousel, 160);
    lv_obj_set_x(ui_panel_carousel, 0);
    lv_obj_set_y(ui_panel_carousel, 78);
    lv_obj_set_flex_flow(ui_panel_carousel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_carousel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_panel_carousel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_carousel, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_carousel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_carousel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_carousel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_carousel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_carousel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_carousel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_carousel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day1 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day1, 130);
    lv_obj_set_height(ui_btn_day1, 140);
    lv_obj_set_x(ui_btn_day1, 13);
    lv_obj_set_y(ui_btn_day1, 16);
    lv_obj_add_flag(ui_btn_day1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day1, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day1, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day1, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day1, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day1, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day1, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name = lv_label_create(ui_btn_day1);
    lv_obj_set_width(ui_lbl_day_name, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name, 0);
    lv_obj_set_y(ui_lbl_day_name, -50);
    lv_obj_set_align(ui_lbl_day_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name, "Monday");
    lv_obj_set_style_text_color(ui_lbl_day_name, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon = lv_image_create(ui_btn_day1);
    lv_obj_set_width(ui_img_day_icon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi = lv_label_create(ui_btn_day1);
    lv_obj_set_width(ui_lbl_day_hi, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi, 0);
    lv_obj_set_y(ui_lbl_day_hi, 40);
    lv_obj_set_align(ui_lbl_day_hi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo = lv_label_create(ui_btn_day1);
    lv_obj_set_width(ui_lbl_day_lo, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo, 0);
    lv_obj_set_y(ui_lbl_day_lo, 55);
    lv_obj_set_align(ui_lbl_day_lo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day2 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day2, 130);
    lv_obj_set_height(ui_btn_day2, 140);
    lv_obj_set_x(ui_btn_day2, 13);
    lv_obj_set_y(ui_btn_day2, 16);
    lv_obj_add_flag(ui_btn_day2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day2, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day2, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day2, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day2, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name1 = lv_label_create(ui_btn_day2);
    lv_obj_set_width(ui_lbl_day_name1, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name1, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name1, 0);
    lv_obj_set_y(ui_lbl_day_name1, -50);
    lv_obj_set_align(ui_lbl_day_name1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name1, "Tuesday");
    lv_obj_set_style_text_color(ui_lbl_day_name1, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon1 = lv_image_create(ui_btn_day2);
    lv_obj_set_width(ui_img_day_icon1, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi1 = lv_label_create(ui_btn_day2);
    lv_obj_set_width(ui_lbl_day_hi1, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi1, 0);
    lv_obj_set_y(ui_lbl_day_hi1, 40);
    lv_obj_set_align(ui_lbl_day_hi1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi1, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi1, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo1 = lv_label_create(ui_btn_day2);
    lv_obj_set_width(ui_lbl_day_lo1, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo1, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo1, 0);
    lv_obj_set_y(ui_lbl_day_lo1, 55);
    lv_obj_set_align(ui_lbl_day_lo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo1, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo1, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day3 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day3, 130);
    lv_obj_set_height(ui_btn_day3, 140);
    lv_obj_set_x(ui_btn_day3, 13);
    lv_obj_set_y(ui_btn_day3, 16);
    lv_obj_add_flag(ui_btn_day3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day3, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day3, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day3, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day3, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day3, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day3, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name2 = lv_label_create(ui_btn_day3);
    lv_obj_set_width(ui_lbl_day_name2, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name2, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name2, 0);
    lv_obj_set_y(ui_lbl_day_name2, -50);
    lv_obj_set_align(ui_lbl_day_name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name2, "Wednesday");
    lv_obj_set_style_text_color(ui_lbl_day_name2, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon2 = lv_image_create(ui_btn_day3);
    lv_obj_set_width(ui_img_day_icon2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi2 = lv_label_create(ui_btn_day3);
    lv_obj_set_width(ui_lbl_day_hi2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi2, 0);
    lv_obj_set_y(ui_lbl_day_hi2, 40);
    lv_obj_set_align(ui_lbl_day_hi2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi2, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi2, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo2 = lv_label_create(ui_btn_day3);
    lv_obj_set_width(ui_lbl_day_lo2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo2, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo2, 0);
    lv_obj_set_y(ui_lbl_day_lo2, 55);
    lv_obj_set_align(ui_lbl_day_lo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo2, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo2, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day4 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day4, 130);
    lv_obj_set_height(ui_btn_day4, 140);
    lv_obj_set_x(ui_btn_day4, 13);
    lv_obj_set_y(ui_btn_day4, 16);
    lv_obj_add_flag(ui_btn_day4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day4, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day4, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day4, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day4, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day4, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day4, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name3 = lv_label_create(ui_btn_day4);
    lv_obj_set_width(ui_lbl_day_name3, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name3, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name3, 0);
    lv_obj_set_y(ui_lbl_day_name3, -50);
    lv_obj_set_align(ui_lbl_day_name3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name3, "Thursday");
    lv_obj_set_style_text_color(ui_lbl_day_name3, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon3 = lv_image_create(ui_btn_day4);
    lv_obj_set_width(ui_img_day_icon3, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi3 = lv_label_create(ui_btn_day4);
    lv_obj_set_width(ui_lbl_day_hi3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi3, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi3, 0);
    lv_obj_set_y(ui_lbl_day_hi3, 40);
    lv_obj_set_align(ui_lbl_day_hi3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi3, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi3, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo3 = lv_label_create(ui_btn_day4);
    lv_obj_set_width(ui_lbl_day_lo3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo3, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo3, 0);
    lv_obj_set_y(ui_lbl_day_lo3, 55);
    lv_obj_set_align(ui_lbl_day_lo3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo3, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo3, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day5 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day5, 130);
    lv_obj_set_height(ui_btn_day5, 140);
    lv_obj_set_x(ui_btn_day5, 13);
    lv_obj_set_y(ui_btn_day5, 16);
    lv_obj_add_flag(ui_btn_day5, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day5, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day5, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day5, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day5, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day5, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day5, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name4 = lv_label_create(ui_btn_day5);
    lv_obj_set_width(ui_lbl_day_name4, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name4, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name4, 0);
    lv_obj_set_y(ui_lbl_day_name4, -50);
    lv_obj_set_align(ui_lbl_day_name4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name4, "Friday");
    lv_obj_set_style_text_color(ui_lbl_day_name4, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon4 = lv_image_create(ui_btn_day5);
    lv_obj_set_width(ui_img_day_icon4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi4 = lv_label_create(ui_btn_day5);
    lv_obj_set_width(ui_lbl_day_hi4, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi4, 0);
    lv_obj_set_y(ui_lbl_day_hi4, 40);
    lv_obj_set_align(ui_lbl_day_hi4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi4, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi4, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo4 = lv_label_create(ui_btn_day5);
    lv_obj_set_width(ui_lbl_day_lo4, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo4, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo4, 0);
    lv_obj_set_y(ui_lbl_day_lo4, 55);
    lv_obj_set_align(ui_lbl_day_lo4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo4, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo4, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day6 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day6, 130);
    lv_obj_set_height(ui_btn_day6, 140);
    lv_obj_set_x(ui_btn_day6, 13);
    lv_obj_set_y(ui_btn_day6, 16);
    lv_obj_add_flag(ui_btn_day6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day6, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day6, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day6, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day6, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day6, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day6, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name5 = lv_label_create(ui_btn_day6);
    lv_obj_set_width(ui_lbl_day_name5, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name5, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name5, 0);
    lv_obj_set_y(ui_lbl_day_name5, -50);
    lv_obj_set_align(ui_lbl_day_name5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name5, "Saturday");
    lv_obj_set_style_text_color(ui_lbl_day_name5, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon5 = lv_image_create(ui_btn_day6);
    lv_obj_set_width(ui_img_day_icon5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi5 = lv_label_create(ui_btn_day6);
    lv_obj_set_width(ui_lbl_day_hi5, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi5, 0);
    lv_obj_set_y(ui_lbl_day_hi5, 40);
    lv_obj_set_align(ui_lbl_day_hi5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi5, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi5, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo5 = lv_label_create(ui_btn_day6);
    lv_obj_set_width(ui_lbl_day_lo5, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo5, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo5, 0);
    lv_obj_set_y(ui_lbl_day_lo5, 55);
    lv_obj_set_align(ui_lbl_day_lo5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo5, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo5, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_day7 = lv_button_create(ui_panel_carousel);
    lv_obj_set_width(ui_btn_day7, 130);
    lv_obj_set_height(ui_btn_day7, 140);
    lv_obj_set_x(ui_btn_day7, 13);
    lv_obj_set_y(ui_btn_day7, 16);
    lv_obj_add_flag(ui_btn_day7, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_day7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_day7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_day7, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_day7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_day7, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_day7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_day7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btn_day7, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btn_day7, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_day7, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_btn_day7, lv_color_hex(0x4A6FA5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_btn_day7, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_btn_day7, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_day_name6 = lv_label_create(ui_btn_day7);
    lv_obj_set_width(ui_lbl_day_name6, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_lbl_day_name6, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_name6, 0);
    lv_obj_set_y(ui_lbl_day_name6, -50);
    lv_obj_set_align(ui_lbl_day_name6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_name6, "Sunday");
    lv_obj_set_style_text_color(ui_lbl_day_name6, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_name6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_day_icon6 = lv_image_create(ui_btn_day7);
    lv_obj_set_width(ui_img_day_icon6, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_day_icon6, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_img_day_icon6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_day_icon6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_day_icon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_day_hi6 = lv_label_create(ui_btn_day7);
    lv_obj_set_width(ui_lbl_day_hi6, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_hi6, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_lbl_day_hi6, 0);
    lv_obj_set_y(ui_lbl_day_hi6, 40);
    lv_obj_set_align(ui_lbl_day_hi6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_hi6, "+12°C");
    lv_obj_set_style_text_color(ui_lbl_day_hi6, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_hi6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_day_lo6 = lv_label_create(ui_btn_day7);
    lv_obj_set_width(ui_lbl_day_lo6, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_lbl_day_lo6, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_day_lo6, 0);
    lv_obj_set_y(ui_lbl_day_lo6, 55);
    lv_obj_set_align(ui_lbl_day_lo6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_day_lo6, "-2°C");
    lv_obj_set_style_text_color(ui_lbl_day_lo6, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_day_lo6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_detail = lv_obj_create(ui_scr_weather);
    lv_obj_set_width(ui_panel_detail, 1024);
    lv_obj_set_height(ui_panel_detail, 362);
    lv_obj_set_x(ui_panel_detail, 0);
    lv_obj_set_y(ui_panel_detail, 238);
    lv_obj_remove_flag(ui_panel_detail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_detail, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_detail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_detail, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_detail_name = lv_label_create(ui_panel_detail);
    lv_obj_set_width(ui_lbl_detail_name, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_lbl_detail_name, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lbl_detail_name, 50);
    lv_obj_set_y(ui_lbl_detail_name, 10);
    lv_label_set_text(ui_lbl_detail_name, "Monday ");
    lv_obj_set_style_text_color(ui_lbl_detail_name, lv_color_hex(0xE0E0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_detail_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_detail_name, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_detail_desc = lv_label_create(ui_panel_detail);
    lv_obj_set_width(ui_lbl_detail_desc, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_lbl_detail_desc, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lbl_detail_desc, 220);
    lv_obj_set_y(ui_lbl_detail_desc, 10);
    lv_label_set_text(ui_lbl_detail_desc, "Partly cloudy");
    lv_obj_set_style_text_color(ui_lbl_detail_desc, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_detail_desc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_detail_hi = lv_label_create(ui_panel_detail);
    lv_obj_set_width(ui_lbl_detail_hi, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_lbl_detail_hi, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lbl_detail_hi, 750);
    lv_obj_set_y(ui_lbl_detail_hi, 10);
    lv_label_set_text(ui_lbl_detail_hi, "Max +12°");
    lv_obj_set_style_text_color(ui_lbl_detail_hi, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_detail_hi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_detail_lo = lv_label_create(ui_panel_detail);
    lv_obj_set_width(ui_lbl_detail_lo, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_lbl_detail_lo, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lbl_detail_lo, 860);
    lv_obj_set_y(ui_lbl_detail_lo, 10);
    lv_label_set_text(ui_lbl_detail_lo, "Min -2°");
    lv_obj_set_style_text_color(ui_lbl_detail_lo, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_detail_lo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_hours = lv_obj_create(ui_panel_detail);
    lv_obj_set_width(ui_panel_hours, 1024);
    lv_obj_set_height(ui_panel_hours, 318);
    lv_obj_set_x(ui_panel_hours, 0);
    lv_obj_set_y(ui_panel_hours, 44);
    lv_obj_set_flex_flow(ui_panel_hours, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_hours, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_panel_hours, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_hours, lv_color_hex(0x252538), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_hours, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_hour1 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour1, 100);
    lv_obj_set_height(ui_panel_hour1, 295);
    lv_obj_set_x(ui_panel_hour1, 10);
    lv_obj_set_y(ui_panel_hour1, 10);
    lv_obj_remove_flag(ui_panel_hour1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour1, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour1, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time1 = lv_label_create(ui_panel_hour1);
    lv_obj_set_width(ui_lbl_hour_time1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time1, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time1, 0);
    lv_obj_set_y(ui_lbl_hour_time1, -115);
    lv_obj_set_align(ui_lbl_hour_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time1, "06:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time1, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp1 = lv_label_create(ui_panel_hour1);
    lv_obj_set_width(ui_lbl_hour_temp1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp1, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp1, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip1 = lv_label_create(ui_panel_hour1);
    lv_obj_set_width(ui_lbl_hour_precip1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip1, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip1, 0);
    lv_obj_set_y(ui_lbl_hour_precip1, 18);
    lv_obj_set_align(ui_lbl_hour_precip1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip1, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip1, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon1 = lv_image_create(ui_panel_hour1);
    lv_obj_set_width(ui_img_hour_icon1, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon1, 0);
    lv_obj_set_y(ui_img_hour_icon1, 32);
    lv_obj_add_flag(ui_img_hour_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour2 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour2, 100);
    lv_obj_set_height(ui_panel_hour2, 295);
    lv_obj_set_x(ui_panel_hour2, 10);
    lv_obj_set_y(ui_panel_hour2, 10);
    lv_obj_remove_flag(ui_panel_hour2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour2, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour2, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time2 = lv_label_create(ui_panel_hour2);
    lv_obj_set_width(ui_lbl_hour_time2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time2, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time2, 0);
    lv_obj_set_y(ui_lbl_hour_time2, -115);
    lv_obj_set_align(ui_lbl_hour_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time2, "08:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time2, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp2 = lv_label_create(ui_panel_hour2);
    lv_obj_set_width(ui_lbl_hour_temp2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp2, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp2, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp2, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip2 = lv_label_create(ui_panel_hour2);
    lv_obj_set_width(ui_lbl_hour_precip2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip2, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip2, 0);
    lv_obj_set_y(ui_lbl_hour_precip2, 18);
    lv_obj_set_align(ui_lbl_hour_precip2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip2, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip2, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon2 = lv_image_create(ui_panel_hour2);
    lv_obj_set_width(ui_img_hour_icon2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon2, 0);
    lv_obj_set_y(ui_img_hour_icon2, 32);
    lv_obj_add_flag(ui_img_hour_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour3 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour3, 100);
    lv_obj_set_height(ui_panel_hour3, 295);
    lv_obj_set_x(ui_panel_hour3, 10);
    lv_obj_set_y(ui_panel_hour3, 10);
    lv_obj_remove_flag(ui_panel_hour3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour3, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour3, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time3 = lv_label_create(ui_panel_hour3);
    lv_obj_set_width(ui_lbl_hour_time3, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time3, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time3, 0);
    lv_obj_set_y(ui_lbl_hour_time3, -115);
    lv_obj_set_align(ui_lbl_hour_time3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time3, "10:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time3, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp3 = lv_label_create(ui_panel_hour3);
    lv_obj_set_width(ui_lbl_hour_temp3, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp3, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp3, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp3, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip3 = lv_label_create(ui_panel_hour3);
    lv_obj_set_width(ui_lbl_hour_precip3, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip3, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip3, 0);
    lv_obj_set_y(ui_lbl_hour_precip3, 18);
    lv_obj_set_align(ui_lbl_hour_precip3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip3, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip3, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon3 = lv_image_create(ui_panel_hour3);
    lv_obj_set_width(ui_img_hour_icon3, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon3, 0);
    lv_obj_set_y(ui_img_hour_icon3, 32);
    lv_obj_add_flag(ui_img_hour_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour4 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour4, 100);
    lv_obj_set_height(ui_panel_hour4, 295);
    lv_obj_set_x(ui_panel_hour4, 10);
    lv_obj_set_y(ui_panel_hour4, 10);
    lv_obj_remove_flag(ui_panel_hour4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour4, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour4, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time4 = lv_label_create(ui_panel_hour4);
    lv_obj_set_width(ui_lbl_hour_time4, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time4, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time4, 0);
    lv_obj_set_y(ui_lbl_hour_time4, -115);
    lv_obj_set_align(ui_lbl_hour_time4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time4, "12:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time4, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp4 = lv_label_create(ui_panel_hour4);
    lv_obj_set_width(ui_lbl_hour_temp4, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp4, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp4, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip4 = lv_label_create(ui_panel_hour4);
    lv_obj_set_width(ui_lbl_hour_precip4, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip4, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip4, 0);
    lv_obj_set_y(ui_lbl_hour_precip4, 18);
    lv_obj_set_align(ui_lbl_hour_precip4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip4, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip4, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon4 = lv_image_create(ui_panel_hour4);
    lv_obj_set_width(ui_img_hour_icon4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon4, 0);
    lv_obj_set_y(ui_img_hour_icon4, 32);
    lv_obj_add_flag(ui_img_hour_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour5 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour5, 100);
    lv_obj_set_height(ui_panel_hour5, 295);
    lv_obj_set_x(ui_panel_hour5, 10);
    lv_obj_set_y(ui_panel_hour5, 10);
    lv_obj_remove_flag(ui_panel_hour5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour5, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour5, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time5 = lv_label_create(ui_panel_hour5);
    lv_obj_set_width(ui_lbl_hour_time5, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time5, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time5, 0);
    lv_obj_set_y(ui_lbl_hour_time5, -115);
    lv_obj_set_align(ui_lbl_hour_time5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time5, "14:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time5, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp5 = lv_label_create(ui_panel_hour5);
    lv_obj_set_width(ui_lbl_hour_temp5, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp5, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp5, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp5, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip5 = lv_label_create(ui_panel_hour5);
    lv_obj_set_width(ui_lbl_hour_precip5, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip5, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip5, 0);
    lv_obj_set_y(ui_lbl_hour_precip5, 18);
    lv_obj_set_align(ui_lbl_hour_precip5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip5, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip5, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon5 = lv_image_create(ui_panel_hour5);
    lv_obj_set_width(ui_img_hour_icon5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon5, 0);
    lv_obj_set_y(ui_img_hour_icon5, 32);
    lv_obj_add_flag(ui_img_hour_icon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour6 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour6, 100);
    lv_obj_set_height(ui_panel_hour6, 295);
    lv_obj_set_x(ui_panel_hour6, 10);
    lv_obj_set_y(ui_panel_hour6, 10);
    lv_obj_remove_flag(ui_panel_hour6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour6, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour6, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time6 = lv_label_create(ui_panel_hour6);
    lv_obj_set_width(ui_lbl_hour_time6, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time6, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time6, 0);
    lv_obj_set_y(ui_lbl_hour_time6, -115);
    lv_obj_set_align(ui_lbl_hour_time6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time6, "16:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time6, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp6 = lv_label_create(ui_panel_hour6);
    lv_obj_set_width(ui_lbl_hour_temp6, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp6, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp6, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp6, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip6 = lv_label_create(ui_panel_hour6);
    lv_obj_set_width(ui_lbl_hour_precip6, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip6, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip6, 0);
    lv_obj_set_y(ui_lbl_hour_precip6, 18);
    lv_obj_set_align(ui_lbl_hour_precip6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip6, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip6, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon6 = lv_image_create(ui_panel_hour6);
    lv_obj_set_width(ui_img_hour_icon6, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon6, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon6, 0);
    lv_obj_set_y(ui_img_hour_icon6, 32);
    lv_obj_add_flag(ui_img_hour_icon6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour7 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour7, 100);
    lv_obj_set_height(ui_panel_hour7, 295);
    lv_obj_set_x(ui_panel_hour7, 10);
    lv_obj_set_y(ui_panel_hour7, 10);
    lv_obj_remove_flag(ui_panel_hour7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour7, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour7, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time7 = lv_label_create(ui_panel_hour7);
    lv_obj_set_width(ui_lbl_hour_time7, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time7, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time7, 0);
    lv_obj_set_y(ui_lbl_hour_time7, -115);
    lv_obj_set_align(ui_lbl_hour_time7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time7, "18:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time7, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp7 = lv_label_create(ui_panel_hour7);
    lv_obj_set_width(ui_lbl_hour_temp7, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp7, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp7, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp7, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip7 = lv_label_create(ui_panel_hour7);
    lv_obj_set_width(ui_lbl_hour_precip7, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip7, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip7, 0);
    lv_obj_set_y(ui_lbl_hour_precip7, 18);
    lv_obj_set_align(ui_lbl_hour_precip7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip7, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip7, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon7 = lv_image_create(ui_panel_hour7);
    lv_obj_set_width(ui_img_hour_icon7, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon7, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon7, 0);
    lv_obj_set_y(ui_img_hour_icon7, 32);
    lv_obj_add_flag(ui_img_hour_icon7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour8 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour8, 100);
    lv_obj_set_height(ui_panel_hour8, 295);
    lv_obj_set_x(ui_panel_hour8, 10);
    lv_obj_set_y(ui_panel_hour8, 10);
    lv_obj_remove_flag(ui_panel_hour8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour8, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour8, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time8 = lv_label_create(ui_panel_hour8);
    lv_obj_set_width(ui_lbl_hour_time8, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time8, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time8, 0);
    lv_obj_set_y(ui_lbl_hour_time8, -115);
    lv_obj_set_align(ui_lbl_hour_time8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time8, "20:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time8, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp8 = lv_label_create(ui_panel_hour8);
    lv_obj_set_width(ui_lbl_hour_temp8, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp8, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp8, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp8, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip8 = lv_label_create(ui_panel_hour8);
    lv_obj_set_width(ui_lbl_hour_precip8, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip8, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip8, 0);
    lv_obj_set_y(ui_lbl_hour_precip8, 18);
    lv_obj_set_align(ui_lbl_hour_precip8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip8, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip8, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon8 = lv_image_create(ui_panel_hour8);
    lv_obj_set_width(ui_img_hour_icon8, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon8, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon8, 0);
    lv_obj_set_y(ui_img_hour_icon8, 32);
    lv_obj_add_flag(ui_img_hour_icon8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_hour9 = lv_obj_create(ui_panel_hours);
    lv_obj_set_width(ui_panel_hour9, 100);
    lv_obj_set_height(ui_panel_hour9, 295);
    lv_obj_set_x(ui_panel_hour9, 10);
    lv_obj_set_y(ui_panel_hour9, 10);
    lv_obj_remove_flag(ui_panel_hour9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_hour9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_hour9, lv_color_hex(0x2A2A3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_hour9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_hour9, lv_color_hex(0x3A3A52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_hour9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_hour9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_time9 = lv_label_create(ui_panel_hour9);
    lv_obj_set_width(ui_lbl_hour_time9, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_time9, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_time9, 0);
    lv_obj_set_y(ui_lbl_hour_time9, -115);
    lv_obj_set_align(ui_lbl_hour_time9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_time9, "22:00");
    lv_obj_set_style_text_color(ui_lbl_hour_time9, lv_color_hex(0x8888AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_time9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_temp9 = lv_label_create(ui_panel_hour9);
    lv_obj_set_width(ui_lbl_hour_temp9, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_temp9, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_lbl_hour_temp9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_temp9, "+3°C");
    lv_obj_set_style_text_color(ui_lbl_hour_temp9, lv_color_hex(0xFF8A65), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_temp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_hour_precip9 = lv_label_create(ui_panel_hour9);
    lv_obj_set_width(ui_lbl_hour_precip9, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_lbl_hour_precip9, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lbl_hour_precip9, 0);
    lv_obj_set_y(ui_lbl_hour_precip9, 18);
    lv_obj_set_align(ui_lbl_hour_precip9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_hour_precip9, "3%");
    lv_obj_set_style_text_color(ui_lbl_hour_precip9, lv_color_hex(0x64B5F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_hour_precip9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_hour_icon9 = lv_image_create(ui_panel_hour9);
    lv_obj_set_width(ui_img_hour_icon9, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_img_hour_icon9, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_img_hour_icon9, 0);
    lv_obj_set_y(ui_img_hour_icon9, 32);
    lv_obj_add_flag(ui_img_hour_icon9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_img_hour_icon9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_scr_weather = ui_scr_weather;
    uic_panel_carousel = ui_panel_carousel;
    uic_lbl_day_name = ui_lbl_day_name;
    uic_img_day_icon = ui_img_day_icon;
    uic_lbl_day_hi = ui_lbl_day_hi;
    uic_lbl_day_lo = ui_lbl_day_lo;
    uic_panel_detail = ui_panel_detail;
    uic_lbl_datail_name = ui_lbl_detail_name;
    uic_lbl_detail_desc = ui_lbl_detail_desc;
    uic_lbl_detail_hi = ui_lbl_detail_hi;
    uic_lbl_detail_lo = ui_lbl_detail_lo;
    uic_panel_hours = ui_panel_hours;
    uic_panel_hour1 = ui_panel_hour1;
    uic_lbl_hour_time1 = ui_lbl_hour_time1;
    uic_lbl_hour_temp1 = ui_lbl_hour_temp1;
    uic_lbl_hour_precip1 = ui_lbl_hour_precip1;
    uic_img_hour_icon1 = ui_img_hour_icon1;

}

void ui_scr_weather_screen_destroy(void)
{
    if(ui_scr_weather) lv_obj_del(ui_scr_weather);

    // NULL screen variables
    uic_scr_weather = NULL;
    ui_scr_weather = NULL;
    ui_panel_navbar1 = NULL;
    ui_btn_home2 = NULL;
    ui_lbl_navabar_home2 = NULL;
    ui_btn__weather2 = NULL;
    ui_lbl_navabar_weather2 = NULL;
    ui_btn_elpris2 = NULL;
    ui_lbl_navabar_elpris2 = NULL;
    ui_btn_settings2 = NULL;
    ui_lbl_navabar_settings2 = NULL;
    ui_panel_status2 = NULL;
    ui_Label3 = NULL;
    uic_panel_carousel = NULL;
    ui_panel_carousel = NULL;
    ui_btn_day1 = NULL;
    uic_lbl_day_name = NULL;
    ui_lbl_day_name = NULL;
    uic_img_day_icon = NULL;
    ui_img_day_icon = NULL;
    uic_lbl_day_hi = NULL;
    ui_lbl_day_hi = NULL;
    uic_lbl_day_lo = NULL;
    ui_lbl_day_lo = NULL;
    ui_btn_day2 = NULL;
    ui_lbl_day_name1 = NULL;
    ui_img_day_icon1 = NULL;
    ui_lbl_day_hi1 = NULL;
    ui_lbl_day_lo1 = NULL;
    ui_btn_day3 = NULL;
    ui_lbl_day_name2 = NULL;
    ui_img_day_icon2 = NULL;
    ui_lbl_day_hi2 = NULL;
    ui_lbl_day_lo2 = NULL;
    ui_btn_day4 = NULL;
    ui_lbl_day_name3 = NULL;
    ui_img_day_icon3 = NULL;
    ui_lbl_day_hi3 = NULL;
    ui_lbl_day_lo3 = NULL;
    ui_btn_day5 = NULL;
    ui_lbl_day_name4 = NULL;
    ui_img_day_icon4 = NULL;
    ui_lbl_day_hi4 = NULL;
    ui_lbl_day_lo4 = NULL;
    ui_btn_day6 = NULL;
    ui_lbl_day_name5 = NULL;
    ui_img_day_icon5 = NULL;
    ui_lbl_day_hi5 = NULL;
    ui_lbl_day_lo5 = NULL;
    ui_btn_day7 = NULL;
    ui_lbl_day_name6 = NULL;
    ui_img_day_icon6 = NULL;
    ui_lbl_day_hi6 = NULL;
    ui_lbl_day_lo6 = NULL;
    uic_panel_detail = NULL;
    ui_panel_detail = NULL;
    uic_lbl_datail_name = NULL;
    ui_lbl_detail_name = NULL;
    uic_lbl_detail_desc = NULL;
    ui_lbl_detail_desc = NULL;
    uic_lbl_detail_hi = NULL;
    ui_lbl_detail_hi = NULL;
    uic_lbl_detail_lo = NULL;
    ui_lbl_detail_lo = NULL;
    uic_panel_hours = NULL;
    ui_panel_hours = NULL;
    uic_panel_hour1 = NULL;
    ui_panel_hour1 = NULL;
    uic_lbl_hour_time1 = NULL;
    ui_lbl_hour_time1 = NULL;
    uic_lbl_hour_temp1 = NULL;
    ui_lbl_hour_temp1 = NULL;
    uic_lbl_hour_precip1 = NULL;
    ui_lbl_hour_precip1 = NULL;
    uic_img_hour_icon1 = NULL;
    ui_img_hour_icon1 = NULL;
    ui_panel_hour2 = NULL;
    ui_lbl_hour_time2 = NULL;
    ui_lbl_hour_temp2 = NULL;
    ui_lbl_hour_precip2 = NULL;
    ui_img_hour_icon2 = NULL;
    ui_panel_hour3 = NULL;
    ui_lbl_hour_time3 = NULL;
    ui_lbl_hour_temp3 = NULL;
    ui_lbl_hour_precip3 = NULL;
    ui_img_hour_icon3 = NULL;
    ui_panel_hour4 = NULL;
    ui_lbl_hour_time4 = NULL;
    ui_lbl_hour_temp4 = NULL;
    ui_lbl_hour_precip4 = NULL;
    ui_img_hour_icon4 = NULL;
    ui_panel_hour5 = NULL;
    ui_lbl_hour_time5 = NULL;
    ui_lbl_hour_temp5 = NULL;
    ui_lbl_hour_precip5 = NULL;
    ui_img_hour_icon5 = NULL;
    ui_panel_hour6 = NULL;
    ui_lbl_hour_time6 = NULL;
    ui_lbl_hour_temp6 = NULL;
    ui_lbl_hour_precip6 = NULL;
    ui_img_hour_icon6 = NULL;
    ui_panel_hour7 = NULL;
    ui_lbl_hour_time7 = NULL;
    ui_lbl_hour_temp7 = NULL;
    ui_lbl_hour_precip7 = NULL;
    ui_img_hour_icon7 = NULL;
    ui_panel_hour8 = NULL;
    ui_lbl_hour_time8 = NULL;
    ui_lbl_hour_temp8 = NULL;
    ui_lbl_hour_precip8 = NULL;
    ui_img_hour_icon8 = NULL;
    ui_panel_hour9 = NULL;
    ui_lbl_hour_time9 = NULL;
    ui_lbl_hour_temp9 = NULL;
    ui_lbl_hour_precip9 = NULL;
    ui_img_hour_icon9 = NULL;

}
