// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_SETTINGS_H
#define UI_SCR_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_settings
extern void ui_scr_settings_screen_init(void);
extern void ui_scr_settings_screen_destroy(void);
extern lv_obj_t * ui_scr_settings;
extern lv_obj_t * ui_panel_navbar4;
extern lv_obj_t * ui_btn_home4;
extern lv_obj_t * ui_lbl_navabar_home4;
extern lv_obj_t * ui_btn__weather4;
extern lv_obj_t * ui_lbl_navabar_weather4;
extern lv_obj_t * ui_btn_elpris4;
extern lv_obj_t * ui_lbl_navabar_elpris4;
extern lv_obj_t * ui_btn_settings4;
extern lv_obj_t * ui_lbl_navabar_settings4;
extern lv_obj_t * ui_panel_status4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_panel_settings_main;
extern lv_obj_t * ui_panel_wifi;
extern lv_obj_t * ui_lbl_wifi_title;
extern lv_obj_t * ui_lbl_wifi_sub;
extern lv_obj_t * ui_lbl_wifi_name;
extern lv_obj_t * ui_btn_wifi_change;
extern lv_obj_t * ui_lbl_btn_wifi_change;
extern lv_obj_t * ui_sw_wifi;
extern lv_obj_t * ui_panel_location;
extern lv_obj_t * ui_lbl_loc_title;
extern lv_obj_t * ui_lbl_loc_sub;
extern lv_obj_t * ui_txt_area_loc_input;
extern lv_obj_t * ui_panel_price;
extern lv_obj_t * ui_lbl_price_title;
extern lv_obj_t * ui_lbl_price_sub;
extern lv_obj_t * ui_dd_price;
extern lv_obj_t * ui_panel_timeout;
extern lv_obj_t * ui_lbl_timeout_title;
extern lv_obj_t * ui_lbl_timeout_sub;
extern lv_obj_t * ui_Dropdown2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_settings;
extern lv_obj_t * uic_panel_settings_main;
extern lv_obj_t * uic_panel_wifi;
extern lv_obj_t * uic_lbl_wifi_title;
extern lv_obj_t * uic_lbl_wifi_sub;
extern lv_obj_t * uic_btn_wifi_change;
extern lv_obj_t * uic_lbl_btn_wifi_change;
extern lv_obj_t * uic_sw_wifi;
extern lv_obj_t * uic_panel_location;
extern lv_obj_t * uic_lbl_loc_title;
extern lv_obj_t * uic_lbl_loc_sub;
extern lv_obj_t * uic_txt_area_loc_input;
extern lv_obj_t * uic_panel_price;
extern lv_obj_t * uic_lbl_price_title;
extern lv_obj_t * uic_dd_price;
extern lv_obj_t * uic_panel_timeout;
extern lv_obj_t * uic_lbl_timeout_title;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

