// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_HOME_H
#define UI_SCR_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_home
extern void ui_scr_home_screen_init(void);
extern void ui_scr_home_screen_destroy(void);
extern lv_obj_t * ui_scr_home;
extern lv_obj_t * ui_panel_navbar;
extern lv_obj_t * ui_btn_home;
extern lv_obj_t * ui_lbl_navabar_home;
extern lv_obj_t * ui_btn__weather;
extern lv_obj_t * ui_lbl_navabar_weather;
extern lv_obj_t * ui_btn_elpris;
extern lv_obj_t * ui_lbl_navabar_elpris;
extern lv_obj_t * ui_btn_settings;
extern lv_obj_t * ui_lbl_navabar_settings;
extern lv_obj_t * ui_panel_status;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_panel_left;
extern lv_obj_t * ui_arc_temp;
extern lv_obj_t * ui_lbl_temp_val;
extern lv_obj_t * ui_lbl_temp_unit;
extern lv_obj_t * ui_arc_pressure;
extern lv_obj_t * ui_lbl_press_val;
extern lv_obj_t * ui_lbl_press_unit;
extern lv_obj_t * ui_arc_humidity;
extern lv_obj_t * ui_lbl_hum_val;
extern lv_obj_t * ui_lbl_hum_unit;
extern lv_obj_t * ui_panel_right;
extern lv_obj_t * ui_panel__current_weather;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_lbl_w_temp;
extern lv_obj_t * ui_lbl_w_temp_hi;
extern lv_obj_t * ui_lbl_w_temp_lo;
extern lv_obj_t * ui_lbl_w_desc;
extern lv_obj_t * ui_lbl_w_loc;
extern lv_obj_t * ui_panel_stat_wind;
extern lv_obj_t * ui_labl_stat_wind_;
extern lv_obj_t * ui_labl_stat_wind_val;
extern lv_obj_t * ui_panel_stat_feels;
extern lv_obj_t * ui_labl_stat_feels;
extern lv_obj_t * ui_labl_stat_feels_val;
extern lv_obj_t * ui_panel_stat_sunrise;
extern lv_obj_t * ui_labl_stat_sunrise;
extern lv_obj_t * ui_lbl_stat_sunrise_val;
extern lv_obj_t * ui_panel_stat_sunset;
extern lv_obj_t * ui_labl_stat_sunset;
extern lv_obj_t * ui_lbl_stat_sunset_val;
extern lv_obj_t * ui_panel_elec_rec;
extern lv_obj_t * ui_lbl_elec_status;
extern lv_obj_t * ui_lbl_elec_sub;
extern lv_obj_t * ui_lbl_elec_price;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_home;
extern lv_obj_t * uic_panel_navbar;
extern lv_obj_t * uic_btn_home;
extern lv_obj_t * uic_lbl_navabar_home;
extern lv_obj_t * uic_btn__weather;
extern lv_obj_t * uic_btn_elpris;
extern lv_obj_t * uic_btn_settings;
extern lv_obj_t * uic_lbl_navabar_settings;
extern lv_obj_t * uic_panel_left;
extern lv_obj_t * uic_arc_temp;
extern lv_obj_t * uic_lbl_temp_val;
extern lv_obj_t * uic_arc_pressure;
extern lv_obj_t * uic_lbl_press_unit;
extern lv_obj_t * uic_arc_humidity;
extern lv_obj_t * uic_lbl_hum_val;
extern lv_obj_t * uic_lbl_hum_unit;
extern lv_obj_t * uic_panel_right;
extern lv_obj_t * uic_panel__current_weather;
extern lv_obj_t * uic_lbl_w_temp_hi;
extern lv_obj_t * uic_lbl_w_temp_lo;
extern lv_obj_t * uic_lbl_w_desc;
extern lv_obj_t * uic_lbl_w_loc;
extern lv_obj_t * uic_panel_stat_wind;
extern lv_obj_t * uic_labl_stat_wind_val;
extern lv_obj_t * uic_panel_stat_feels;
extern lv_obj_t * uic_labl_stat_feels;
extern lv_obj_t * uic_labl_stat_feels_val;
extern lv_obj_t * uic_panel_stat_sunrise;
extern lv_obj_t * uic_labl_stat_sunrise;
extern lv_obj_t * uic_lbl_stat_sunrise_val;
extern lv_obj_t * uic_labl_stat_sunset;
extern lv_obj_t * uic_lbl_stat_sunset_val;
extern lv_obj_t * uic_panel_elec_rec;
extern lv_obj_t * uic_lbl_elec_status;
extern lv_obj_t * uic_lbl_elec_sub;
extern lv_obj_t * uic_lbl_elec_price;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

