// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_WEATHER_H
#define UI_SCR_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_weather
extern void ui_scr_weather_screen_init(void);
extern void ui_scr_weather_screen_destroy(void);
extern lv_obj_t * ui_scr_weather;
extern lv_obj_t * ui_panel_navbar1;
extern lv_obj_t * ui_btn_home2;
extern lv_obj_t * ui_lbl_navabar_home2;
extern lv_obj_t * ui_btn__weather2;
extern lv_obj_t * ui_lbl_navabar_weather2;
extern lv_obj_t * ui_btn_elpris2;
extern lv_obj_t * ui_lbl_navabar_elpris2;
extern lv_obj_t * ui_btn_settings2;
extern lv_obj_t * ui_lbl_navabar_settings2;
extern lv_obj_t * ui_panel_status2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_panel_carousel;
extern lv_obj_t * ui_btn_day1;
extern lv_obj_t * ui_lbl_day_name;
extern lv_obj_t * ui_img_day_icon;
extern lv_obj_t * ui_lbl_day_hi;
extern lv_obj_t * ui_lbl_day_lo;
extern lv_obj_t * ui_btn_day2;
extern lv_obj_t * ui_lbl_day_name1;
extern lv_obj_t * ui_img_day_icon1;
extern lv_obj_t * ui_lbl_day_hi1;
extern lv_obj_t * ui_lbl_day_lo1;
extern lv_obj_t * ui_btn_day3;
extern lv_obj_t * ui_lbl_day_name2;
extern lv_obj_t * ui_img_day_icon2;
extern lv_obj_t * ui_lbl_day_hi2;
extern lv_obj_t * ui_lbl_day_lo2;
extern lv_obj_t * ui_btn_day4;
extern lv_obj_t * ui_lbl_day_name3;
extern lv_obj_t * ui_img_day_icon3;
extern lv_obj_t * ui_lbl_day_hi3;
extern lv_obj_t * ui_lbl_day_lo3;
extern lv_obj_t * ui_btn_day5;
extern lv_obj_t * ui_lbl_day_name4;
extern lv_obj_t * ui_img_day_icon4;
extern lv_obj_t * ui_lbl_day_hi4;
extern lv_obj_t * ui_lbl_day_lo4;
extern lv_obj_t * ui_btn_day6;
extern lv_obj_t * ui_lbl_day_name5;
extern lv_obj_t * ui_img_day_icon5;
extern lv_obj_t * ui_lbl_day_hi5;
extern lv_obj_t * ui_lbl_day_lo5;
extern lv_obj_t * ui_btn_day7;
extern lv_obj_t * ui_lbl_day_name6;
extern lv_obj_t * ui_img_day_icon6;
extern lv_obj_t * ui_lbl_day_hi6;
extern lv_obj_t * ui_lbl_day_lo6;
extern lv_obj_t * ui_panel_detail;
extern lv_obj_t * ui_lbl_detail_name;
extern lv_obj_t * ui_lbl_detail_desc;
extern lv_obj_t * ui_lbl_detail_hi;
extern lv_obj_t * ui_lbl_detail_lo;
extern lv_obj_t * ui_panel_hours;
extern lv_obj_t * ui_panel_hour1;
extern lv_obj_t * ui_lbl_hour_time1;
extern lv_obj_t * ui_lbl_hour_temp1;
extern lv_obj_t * ui_lbl_hour_precip1;
extern lv_obj_t * ui_img_hour_icon1;
extern lv_obj_t * ui_panel_hour2;
extern lv_obj_t * ui_lbl_hour_time2;
extern lv_obj_t * ui_lbl_hour_temp2;
extern lv_obj_t * ui_lbl_hour_precip2;
extern lv_obj_t * ui_img_hour_icon2;
extern lv_obj_t * ui_panel_hour3;
extern lv_obj_t * ui_lbl_hour_time3;
extern lv_obj_t * ui_lbl_hour_temp3;
extern lv_obj_t * ui_lbl_hour_precip3;
extern lv_obj_t * ui_img_hour_icon3;
extern lv_obj_t * ui_panel_hour4;
extern lv_obj_t * ui_lbl_hour_time4;
extern lv_obj_t * ui_lbl_hour_temp4;
extern lv_obj_t * ui_lbl_hour_precip4;
extern lv_obj_t * ui_img_hour_icon4;
extern lv_obj_t * ui_panel_hour5;
extern lv_obj_t * ui_lbl_hour_time5;
extern lv_obj_t * ui_lbl_hour_temp5;
extern lv_obj_t * ui_lbl_hour_precip5;
extern lv_obj_t * ui_img_hour_icon5;
extern lv_obj_t * ui_panel_hour6;
extern lv_obj_t * ui_lbl_hour_time6;
extern lv_obj_t * ui_lbl_hour_temp6;
extern lv_obj_t * ui_lbl_hour_precip6;
extern lv_obj_t * ui_img_hour_icon6;
extern lv_obj_t * ui_panel_hour7;
extern lv_obj_t * ui_lbl_hour_time7;
extern lv_obj_t * ui_lbl_hour_temp7;
extern lv_obj_t * ui_lbl_hour_precip7;
extern lv_obj_t * ui_img_hour_icon7;
extern lv_obj_t * ui_panel_hour8;
extern lv_obj_t * ui_lbl_hour_time8;
extern lv_obj_t * ui_lbl_hour_temp8;
extern lv_obj_t * ui_lbl_hour_precip8;
extern lv_obj_t * ui_img_hour_icon8;
extern lv_obj_t * ui_panel_hour9;
extern lv_obj_t * ui_lbl_hour_time9;
extern lv_obj_t * ui_lbl_hour_temp9;
extern lv_obj_t * ui_lbl_hour_precip9;
extern lv_obj_t * ui_img_hour_icon9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_weather;
extern lv_obj_t * uic_panel_carousel;
extern lv_obj_t * uic_lbl_day_name;
extern lv_obj_t * uic_img_day_icon;
extern lv_obj_t * uic_lbl_day_hi;
extern lv_obj_t * uic_lbl_day_lo;
extern lv_obj_t * uic_panel_detail;
extern lv_obj_t * uic_lbl_datail_name;
extern lv_obj_t * uic_lbl_detail_desc;
extern lv_obj_t * uic_lbl_detail_hi;
extern lv_obj_t * uic_lbl_detail_lo;
extern lv_obj_t * uic_panel_hours;
extern lv_obj_t * uic_panel_hour1;
extern lv_obj_t * uic_lbl_hour_time1;
extern lv_obj_t * uic_lbl_hour_temp1;
extern lv_obj_t * uic_lbl_hour_precip1;
extern lv_obj_t * uic_img_hour_icon1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

