// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_ELPRIS_H
#define UI_SCR_ELPRIS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_elpris
extern void ui_scr_elpris_screen_init(void);
extern void ui_scr_elpris_screen_destroy(void);
extern lv_obj_t * ui_scr_elpris;
extern lv_obj_t * ui_panel_navbar3;
extern lv_obj_t * ui_btn_home3;
extern lv_obj_t * ui_lbl_navabar_home3;
extern lv_obj_t * ui_btn__weather3;
extern lv_obj_t * ui_lbl_navabar_weather3;
extern lv_obj_t * ui_btn_elpris3;
extern lv_obj_t * ui_lbl_navabar_elpris3;
extern lv_obj_t * ui_btn_settings3;
extern lv_obj_t * ui_lbl_navabar_settings3;
extern lv_obj_t * ui_panel_status3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_panel_price_header;
extern lv_obj_t * ui_lbl_price_now;
extern lv_obj_t * ui_lbl_price_val;
extern lv_obj_t * ui_lbl_price_unit;
extern lv_obj_t * ui_lbl_price_hi;
extern lv_obj_t * ui_lbl_price_lo;
extern lv_obj_t * ui_lbl_price_avg;
extern lv_obj_t * ui_panel_chart;
extern lv_obj_t * ui_chart_elpris;
extern lv_obj_t * ui_chart_elpris_Xaxis;
extern lv_obj_t * ui_chart_elpris_Yaxis1;
extern lv_obj_t * ui_chart_elpris_Yaxis2;
extern lv_obj_t * ui_lbl_leg_cheap;
extern lv_obj_t * ui_lbl_leg_avg;
extern lv_obj_t * ui_lbl_leg_exp;
extern lv_obj_t * ui_lbl_leg_now;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_elpris;
extern lv_obj_t * uic_panel_price_header;
extern lv_obj_t * uic_lbl_price_now;
extern lv_obj_t * uic_lbl_price_val;
extern lv_obj_t * uic_lbl_price_unit;
extern lv_obj_t * uic_lbl_price_hi;
extern lv_obj_t * uic_lbl_price_lo;
extern lv_obj_t * uic_lbl_price_avg;
extern lv_obj_t * uic_chart_elpris;
extern lv_obj_t * uic_lbl_leg_cheap;
extern lv_obj_t * uic_lbl_leg_exp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

