// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#include "../ui.h"

lv_obj_t* uic_lbl_timeout_title;
lv_obj_t* uic_panel_timeout;
lv_obj_t* uic_dd_price;
lv_obj_t* uic_lbl_price_title;
lv_obj_t* uic_panel_price;
lv_obj_t* uic_txt_area_loc_input;
lv_obj_t* uic_lbl_loc_sub;
lv_obj_t* uic_lbl_loc_title;
lv_obj_t* uic_panel_location;
lv_obj_t* uic_sw_wifi;
lv_obj_t* uic_lbl_btn_wifi_change;
lv_obj_t* uic_btn_wifi_change;
lv_obj_t* uic_lbl_wifi_sub;
lv_obj_t* uic_lbl_wifi_title;
lv_obj_t* uic_panel_wifi;
lv_obj_t* uic_panel_settings_main;
lv_obj_t* uic_scr_settings;
lv_obj_t* ui_scr_settings          = NULL;
lv_obj_t* ui_panel_navbar4         = NULL;
lv_obj_t* ui_btn_home4             = NULL;
lv_obj_t* ui_lbl_navabar_home4     = NULL;
lv_obj_t* ui_btn__weather4         = NULL;
lv_obj_t* ui_lbl_navabar_weather4  = NULL;
lv_obj_t* ui_btn_elpris4           = NULL;
lv_obj_t* ui_lbl_navabar_elpris4   = NULL;
lv_obj_t* ui_btn_settings4         = NULL;
lv_obj_t* ui_lbl_navabar_settings4 = NULL;
lv_obj_t* ui_panel_status4         = NULL;
lv_obj_t* ui_Label5                = NULL;
lv_obj_t* ui_panel_settings_main   = NULL;
lv_obj_t* ui_panel_wifi            = NULL;
lv_obj_t* ui_lbl_wifi_title        = NULL;
lv_obj_t* ui_lbl_wifi_sub          = NULL;
lv_obj_t* ui_lbl_wifi_name         = NULL;
lv_obj_t* ui_btn_wifi_change       = NULL;
lv_obj_t* ui_lbl_btn_wifi_change   = NULL;
lv_obj_t* ui_sw_wifi               = NULL;
lv_obj_t* ui_panel_location        = NULL;
lv_obj_t* ui_lbl_loc_title         = NULL;
lv_obj_t* ui_lbl_loc_sub           = NULL;
lv_obj_t* ui_txt_area_loc_input    = NULL;
lv_obj_t* ui_panel_price           = NULL;
lv_obj_t* ui_lbl_price_title       = NULL;
lv_obj_t* ui_lbl_price_sub         = NULL;
lv_obj_t* ui_dd_price              = NULL;
lv_obj_t* ui_panel_timeout         = NULL;
lv_obj_t* ui_lbl_timeout_title     = NULL;
lv_obj_t* ui_lbl_timeout_sub       = NULL;
lv_obj_t* ui_Dropdown2             = NULL;
// event funtions

// build funtions

void ui_scr_settings_screen_init(void) {
    ui_scr_settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_settings, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_scr_settings, lv_color_hex(0x202439),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_navbar4 = lv_obj_create(ui_scr_settings);
    lv_obj_set_width(ui_panel_navbar4, 1024);
    lv_obj_set_height(ui_panel_navbar4, 78);
    lv_obj_set_x(ui_panel_navbar4, 0);
    lv_obj_set_y(ui_panel_navbar4, -1);
    lv_obj_set_flex_flow(ui_panel_navbar4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_navbar4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_panel_navbar4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_navbar4, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_navbar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_navbar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_navbar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_navbar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_navbar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_navbar4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_navbar4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_home4 = lv_button_create(ui_panel_navbar4);
    lv_obj_set_width(ui_btn_home4, 230);
    lv_obj_set_height(ui_btn_home4, 78);
    lv_obj_set_x(ui_btn_home4, 289);
    lv_obj_set_y(ui_btn_home4, -28);
    lv_obj_add_flag(ui_btn_home4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_home4, LV_OBJ_FLAG_SCROLLABLE);                           /// Flags
    lv_obj_set_style_bg_color(ui_btn_home4, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_home4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_home4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_home4, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_home4, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_home4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_home4, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_home4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_btn_home4, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_btn_home4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_home4 = lv_label_create(ui_btn_home4);
    lv_obj_set_width(ui_lbl_navabar_home4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_home4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_home4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_home4, "HOME");

    ui_btn__weather4 = lv_button_create(ui_panel_navbar4);
    lv_obj_set_width(ui_btn__weather4, 230);
    lv_obj_set_height(ui_btn__weather4, 78);
    lv_obj_add_flag(ui_btn__weather4,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn__weather4, LV_OBJ_FLAG_SCROLLABLE);         /// Flags
    lv_obj_set_style_bg_color(ui_btn__weather4, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn__weather4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn__weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn__weather4, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn__weather4, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn__weather4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn__weather4, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn__weather4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_weather4 = lv_label_create(ui_btn__weather4);
    lv_obj_set_width(ui_lbl_navabar_weather4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_weather4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_weather4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_weather4, "WEATEHER");

    ui_btn_elpris4 = lv_button_create(ui_panel_navbar4);
    lv_obj_set_width(ui_btn_elpris4, 230);
    lv_obj_set_height(ui_btn_elpris4, 78);
    lv_obj_add_flag(ui_btn_elpris4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_elpris4, LV_OBJ_FLAG_SCROLLABLE);                           /// Flags
    lv_obj_set_style_bg_color(ui_btn_elpris4, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_elpris4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_elpris4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_elpris4, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_elpris4, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_elpris4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_elpris4, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_elpris4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_elpris4 = lv_label_create(ui_btn_elpris4);
    lv_obj_set_width(ui_lbl_navabar_elpris4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_elpris4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_elpris4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_elpris4, "ELPRIS");

    ui_btn_settings4 = lv_button_create(ui_panel_navbar4);
    lv_obj_set_width(ui_btn_settings4, 230);
    lv_obj_set_height(ui_btn_settings4, 78);
    lv_obj_add_flag(ui_btn_settings4,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_settings4, LV_OBJ_FLAG_SCROLLABLE);         /// Flags
    lv_obj_set_style_bg_color(ui_btn_settings4, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_settings4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_settings4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_settings4, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_settings4, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_settings4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_settings4, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_settings4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_settings4 = lv_label_create(ui_btn_settings4);
    lv_obj_set_width(ui_lbl_navabar_settings4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_settings4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_settings4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_settings4, "SETTINGS");

    ui_panel_status4 = lv_obj_create(ui_panel_navbar4);
    lv_obj_set_width(ui_panel_status4, 104);
    lv_obj_set_height(ui_panel_status4, 78);
    lv_obj_set_align(ui_panel_status4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel_status4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_status4, lv_color_hex(0x202439),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_status4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_status4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_panel_status4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "$EF WiFi");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_settings_main = lv_obj_create(ui_scr_settings);
    lv_obj_set_width(ui_panel_settings_main, 1024);
    lv_obj_set_height(ui_panel_settings_main, 488);
    lv_obj_set_x(ui_panel_settings_main, 0);
    lv_obj_set_y(ui_panel_settings_main, 78);
    lv_obj_remove_flag(ui_panel_settings_main, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_settings_main, lv_color_hex(0x252535),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_settings_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_settings_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_settings_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_settings_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_settings_main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_settings_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_wifi = lv_obj_create(ui_panel_settings_main);
    lv_obj_set_width(ui_panel_wifi, 984);
    lv_obj_set_height(ui_panel_wifi, 106);
    lv_obj_set_x(ui_panel_wifi, 20);
    lv_obj_set_y(ui_panel_wifi, 11);
    lv_obj_remove_flag(ui_panel_wifi, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_panel_wifi, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_wifi, lv_color_hex(0x2A2A3E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_wifi, lv_color_hex(0x3A3A52),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_wifi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_wifi_title = lv_label_create(ui_panel_wifi);
    lv_obj_set_width(ui_lbl_wifi_title, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_wifi_title, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_wifi_title, 60);
    lv_obj_set_y(ui_lbl_wifi_title, 28);
    lv_label_set_text(ui_lbl_wifi_title, "WIFI");
    lv_obj_set_style_text_color(ui_lbl_wifi_title, lv_color_hex(0xE0E0F0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_wifi_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_wifi_sub = lv_label_create(ui_panel_wifi);
    lv_obj_set_width(ui_lbl_wifi_sub, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_wifi_sub, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_wifi_sub, 60);
    lv_obj_set_y(ui_lbl_wifi_sub, 52);
    lv_label_set_text(ui_lbl_wifi_sub, "Network connection");
    lv_obj_set_style_text_color(ui_lbl_wifi_sub, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_wifi_sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_wifi_name = lv_label_create(ui_panel_wifi);
    lv_obj_set_width(ui_lbl_wifi_name, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_wifi_name, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_wifi_name, 600);
    lv_obj_set_y(ui_lbl_wifi_name, 38);
    lv_label_set_text(ui_lbl_wifi_name, "HomeNetwork_5G");
    lv_obj_set_style_text_color(ui_lbl_wifi_name, lv_color_hex(0x4CAF50),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_wifi_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_wifi_change = lv_button_create(ui_panel_wifi);
    lv_obj_set_width(ui_btn_wifi_change, 90);
    lv_obj_set_height(ui_btn_wifi_change, 30);
    lv_obj_set_x(ui_btn_wifi_change, 790);
    lv_obj_set_y(ui_btn_wifi_change, 33);
    lv_obj_add_flag(ui_btn_wifi_change, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_wifi_change, LV_OBJ_FLAG_SCROLLABLE);   /// Flags

    ui_lbl_btn_wifi_change = lv_label_create(ui_btn_wifi_change);
    lv_obj_set_width(ui_lbl_btn_wifi_change, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_btn_wifi_change, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_btn_wifi_change, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_btn_wifi_change, "Change");

    ui_sw_wifi = lv_switch_create(ui_panel_wifi);
    lv_obj_set_width(ui_sw_wifi, 50);
    lv_obj_set_height(ui_sw_wifi, 26);
    lv_obj_set_x(ui_sw_wifi, 900);
    lv_obj_set_y(ui_sw_wifi, 38);

    ui_panel_location = lv_obj_create(ui_panel_settings_main);
    lv_obj_set_width(ui_panel_location, 984);
    lv_obj_set_height(ui_panel_location, 106);
    lv_obj_set_x(ui_panel_location, 20);
    lv_obj_set_y(ui_panel_location, 126);
    lv_obj_remove_flag(ui_panel_location, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_panel_location, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_location, lv_color_hex(0x2A2A3E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_location, lv_color_hex(0x3A3A52),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_location, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_location, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_location, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_location, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_location, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_loc_title = lv_label_create(ui_panel_location);
    lv_obj_set_width(ui_lbl_loc_title, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_loc_title, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_loc_title, 60);
    lv_obj_set_y(ui_lbl_loc_title, 28);
    lv_label_set_text(ui_lbl_loc_title, "Location");

    ui_lbl_loc_sub = lv_label_create(ui_panel_location);
    lv_obj_set_width(ui_lbl_loc_sub, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_loc_sub, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_loc_sub, 60);
    lv_obj_set_y(ui_lbl_loc_sub, 52);
    lv_label_set_text(ui_lbl_loc_sub, "City for weather data");
    lv_obj_set_style_text_color(ui_lbl_loc_sub, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_loc_sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txt_area_loc_input = lv_textarea_create(ui_panel_location);
    lv_obj_set_width(ui_txt_area_loc_input, 240);
    lv_obj_set_height(ui_txt_area_loc_input, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_txt_area_loc_input, 700);
    lv_obj_set_y(ui_txt_area_loc_input, 33);
    lv_textarea_set_max_length(ui_txt_area_loc_input, 120);
    lv_textarea_set_placeholder_text(ui_txt_area_loc_input, "Placeholder");
    lv_textarea_set_one_line(ui_txt_area_loc_input, true);
    lv_textarea_set_password_mode(ui_txt_area_loc_input, true);

    ui_panel_price = lv_obj_create(ui_panel_settings_main);
    lv_obj_set_width(ui_panel_price, 984);
    lv_obj_set_height(ui_panel_price, 106);
    lv_obj_set_x(ui_panel_price, 20);
    lv_obj_set_y(ui_panel_price, 242);
    lv_obj_remove_flag(ui_panel_price, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_panel_price, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_price, lv_color_hex(0x2A2A3E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_price, lv_color_hex(0x3A3A52),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_price, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_title = lv_label_create(ui_panel_price);
    lv_obj_set_width(ui_lbl_price_title, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_price_title, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_price_title, 60);
    lv_obj_set_y(ui_lbl_price_title, 28);
    lv_label_set_text(ui_lbl_price_title, "Price group");

    ui_lbl_price_sub = lv_label_create(ui_panel_price);
    lv_obj_set_width(ui_lbl_price_sub, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_price_sub, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_price_sub, 60);
    lv_obj_set_y(ui_lbl_price_sub, 52);
    lv_label_set_text(ui_lbl_price_sub, "Swedish electricity zone");
    lv_obj_set_style_text_color(ui_lbl_price_sub, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dd_price = lv_dropdown_create(ui_panel_price);
    lv_dropdown_set_dir(ui_dd_price, LV_DIR_TOP);
    lv_dropdown_set_options(ui_dd_price, "SE 1\nSE 2\nSE 3\nSE 4");
    lv_obj_set_width(ui_dd_price, 120);
    lv_obj_set_height(ui_dd_price, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_dd_price, 840);
    lv_obj_set_y(ui_dd_price, 33);
    lv_obj_add_flag(ui_dd_price, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags

    ui_panel_timeout = lv_obj_create(ui_panel_settings_main);
    lv_obj_set_width(ui_panel_timeout, 984);
    lv_obj_set_height(ui_panel_timeout, 106);
    lv_obj_set_x(ui_panel_timeout, 20);
    lv_obj_set_y(ui_panel_timeout, 358);
    lv_obj_remove_flag(ui_panel_timeout, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_panel_timeout, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_timeout, lv_color_hex(0x2A2A3E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_timeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_timeout, lv_color_hex(0x3A3A52),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_timeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_timeout, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_timeout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_timeout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_timeout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_timeout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_timeout_title = lv_label_create(ui_panel_timeout);
    lv_obj_set_width(ui_lbl_timeout_title, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_timeout_title, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_timeout_title, 60);
    lv_obj_set_y(ui_lbl_timeout_title, 28);
    lv_label_set_text(ui_lbl_timeout_title, "Screen timeout");

    ui_lbl_timeout_sub = lv_label_create(ui_panel_timeout);
    lv_obj_set_width(ui_lbl_timeout_sub, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_lbl_timeout_sub, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_timeout_sub, 60);
    lv_obj_set_y(ui_lbl_timeout_sub, 52);
    lv_label_set_text(ui_lbl_timeout_sub, "Auto dim after inactivity");
    lv_obj_set_style_text_color(ui_lbl_timeout_sub, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_timeout_sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_panel_timeout);
    lv_dropdown_set_dir(ui_Dropdown2, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown2, "5 min	\n10 min\n15 min\n20 min\n25 min\n30 min");
    lv_obj_set_width(ui_Dropdown2, 120);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_Dropdown2, 840);
    lv_obj_set_y(ui_Dropdown2, 33);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags

    uic_scr_settings        = ui_scr_settings;
    uic_panel_settings_main = ui_panel_settings_main;
    uic_panel_wifi          = ui_panel_wifi;
    uic_lbl_wifi_title      = ui_lbl_wifi_title;
    uic_lbl_wifi_sub        = ui_lbl_wifi_sub;
    uic_btn_wifi_change     = ui_btn_wifi_change;
    uic_lbl_btn_wifi_change = ui_lbl_btn_wifi_change;
    uic_sw_wifi             = ui_sw_wifi;
    uic_panel_location      = ui_panel_location;
    uic_lbl_loc_title       = ui_lbl_loc_title;
    uic_lbl_loc_sub         = ui_lbl_loc_sub;
    uic_txt_area_loc_input  = ui_txt_area_loc_input;
    uic_panel_price         = ui_panel_price;
    uic_lbl_price_title     = ui_lbl_price_title;
    uic_dd_price            = ui_dd_price;
    uic_panel_timeout       = ui_panel_timeout;
    uic_lbl_timeout_title   = ui_lbl_timeout_title;
}

void ui_scr_settings_screen_destroy(void) {
    if (ui_scr_settings)
        lv_obj_del(ui_scr_settings);

    // NULL screen variables
    uic_scr_settings         = NULL;
    ui_scr_settings          = NULL;
    ui_panel_navbar4         = NULL;
    ui_btn_home4             = NULL;
    ui_lbl_navabar_home4     = NULL;
    ui_btn__weather4         = NULL;
    ui_lbl_navabar_weather4  = NULL;
    ui_btn_elpris4           = NULL;
    ui_lbl_navabar_elpris4   = NULL;
    ui_btn_settings4         = NULL;
    ui_lbl_navabar_settings4 = NULL;
    ui_panel_status4         = NULL;
    ui_Label5                = NULL;
    uic_panel_settings_main  = NULL;
    ui_panel_settings_main   = NULL;
    uic_panel_wifi           = NULL;
    ui_panel_wifi            = NULL;
    uic_lbl_wifi_title       = NULL;
    ui_lbl_wifi_title        = NULL;
    uic_lbl_wifi_sub         = NULL;
    ui_lbl_wifi_sub          = NULL;
    ui_lbl_wifi_name         = NULL;
    uic_btn_wifi_change      = NULL;
    ui_btn_wifi_change       = NULL;
    uic_lbl_btn_wifi_change  = NULL;
    ui_lbl_btn_wifi_change   = NULL;
    uic_sw_wifi              = NULL;
    ui_sw_wifi               = NULL;
    uic_panel_location       = NULL;
    ui_panel_location        = NULL;
    uic_lbl_loc_title        = NULL;
    ui_lbl_loc_title         = NULL;
    uic_lbl_loc_sub          = NULL;
    ui_lbl_loc_sub           = NULL;
    uic_txt_area_loc_input   = NULL;
    ui_txt_area_loc_input    = NULL;
    uic_panel_price          = NULL;
    ui_panel_price           = NULL;
    uic_lbl_price_title      = NULL;
    ui_lbl_price_title       = NULL;
    ui_lbl_price_sub         = NULL;
    uic_dd_price             = NULL;
    ui_dd_price              = NULL;
    uic_panel_timeout        = NULL;
    ui_panel_timeout         = NULL;
    uic_lbl_timeout_title    = NULL;
    ui_lbl_timeout_title     = NULL;
    ui_lbl_timeout_sub       = NULL;
    ui_Dropdown2             = NULL;
}
