// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#include "../ui.h"

lv_obj_t* uic_lbl_leg_exp;
lv_obj_t* uic_lbl_leg_cheap;
lv_obj_t* uic_chart_elpris;
lv_obj_t* uic_lbl_price_avg;
lv_obj_t* uic_lbl_price_lo;
lv_obj_t* uic_lbl_price_hi;
lv_obj_t* uic_lbl_price_unit;
lv_obj_t* uic_lbl_price_val;
lv_obj_t* uic_lbl_price_now;
lv_obj_t* uic_panel_price_header;
lv_obj_t* uic_scr_elpris;
lv_obj_t* ui_scr_elpris            = NULL;
lv_obj_t* ui_panel_navbar3         = NULL;
lv_obj_t* ui_btn_home3             = NULL;
lv_obj_t* ui_lbl_navabar_home3     = NULL;
lv_obj_t* ui_btn__weather3         = NULL;
lv_obj_t* ui_lbl_navabar_weather3  = NULL;
lv_obj_t* ui_btn_elpris3           = NULL;
lv_obj_t* ui_lbl_navabar_elpris3   = NULL;
lv_obj_t* ui_btn_settings3         = NULL;
lv_obj_t* ui_lbl_navabar_settings3 = NULL;
lv_obj_t* ui_panel_status3         = NULL;
lv_obj_t* ui_Label4                = NULL;
lv_obj_t* ui_panel_price_header    = NULL;
lv_obj_t* ui_lbl_price_now         = NULL;
lv_obj_t* ui_lbl_price_val         = NULL;
lv_obj_t* ui_lbl_price_unit        = NULL;
lv_obj_t* ui_lbl_price_hi          = NULL;
lv_obj_t* ui_lbl_price_lo          = NULL;
lv_obj_t* ui_lbl_price_avg         = NULL;
lv_obj_t* ui_panel_chart           = NULL;
lv_obj_t* ui_chart_elpris          = NULL;
lv_obj_t* ui_chart_elpris_Xaxis    = NULL;
lv_obj_t* ui_chart_elpris_Yaxis1   = NULL;
lv_obj_t* ui_chart_elpris_Yaxis2   = NULL;
lv_obj_t* ui_lbl_leg_cheap         = NULL;
lv_obj_t* ui_lbl_leg_avg           = NULL;
lv_obj_t* ui_lbl_leg_exp           = NULL;
lv_obj_t* ui_lbl_leg_now           = NULL;
// event funtions

// build funtions

void ui_scr_elpris_screen_init(void) {
    ui_scr_elpris = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_elpris, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_scr_elpris, lv_color_hex(0x202439),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_elpris, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_navbar3 = lv_obj_create(ui_scr_elpris);
    lv_obj_set_width(ui_panel_navbar3, 1024);
    lv_obj_set_height(ui_panel_navbar3, 78);
    lv_obj_set_x(ui_panel_navbar3, 0);
    lv_obj_set_y(ui_panel_navbar3, -1);
    lv_obj_set_flex_flow(ui_panel_navbar3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panel_navbar3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_panel_navbar3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_navbar3, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_navbar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_navbar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_navbar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_navbar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_navbar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_navbar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_navbar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_home3 = lv_button_create(ui_panel_navbar3);
    lv_obj_set_width(ui_btn_home3, 230);
    lv_obj_set_height(ui_btn_home3, 78);
    lv_obj_set_x(ui_btn_home3, 289);
    lv_obj_set_y(ui_btn_home3, -28);
    lv_obj_add_flag(ui_btn_home3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_home3, LV_OBJ_FLAG_SCROLLABLE);                           /// Flags
    lv_obj_set_style_bg_color(ui_btn_home3, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_home3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_home3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_home3, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_home3, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_home3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_home3, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_home3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_btn_home3, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_btn_home3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_home3 = lv_label_create(ui_btn_home3);
    lv_obj_set_width(ui_lbl_navabar_home3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_home3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_home3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_home3, "HOME");

    ui_btn__weather3 = lv_button_create(ui_panel_navbar3);
    lv_obj_set_width(ui_btn__weather3, 230);
    lv_obj_set_height(ui_btn__weather3, 78);
    lv_obj_add_flag(ui_btn__weather3,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn__weather3, LV_OBJ_FLAG_SCROLLABLE);         /// Flags
    lv_obj_set_style_bg_color(ui_btn__weather3, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn__weather3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn__weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn__weather3, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn__weather3, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn__weather3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn__weather3, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn__weather3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_weather3 = lv_label_create(ui_btn__weather3);
    lv_obj_set_width(ui_lbl_navabar_weather3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_weather3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_weather3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_weather3, "WEATEHER");

    ui_btn_elpris3 = lv_button_create(ui_panel_navbar3);
    lv_obj_set_width(ui_btn_elpris3, 230);
    lv_obj_set_height(ui_btn_elpris3, 78);
    lv_obj_add_flag(ui_btn_elpris3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_elpris3, LV_OBJ_FLAG_SCROLLABLE);                           /// Flags
    lv_obj_set_style_bg_color(ui_btn_elpris3, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_elpris3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_elpris3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_elpris3, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_elpris3, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_elpris3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_elpris3, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_elpris3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_elpris3 = lv_label_create(ui_btn_elpris3);
    lv_obj_set_width(ui_lbl_navabar_elpris3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_elpris3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_elpris3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_elpris3, "ELPRIS");

    ui_btn_settings3 = lv_button_create(ui_panel_navbar3);
    lv_obj_set_width(ui_btn_settings3, 230);
    lv_obj_set_height(ui_btn_settings3, 78);
    lv_obj_add_flag(ui_btn_settings3,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_btn_settings3, LV_OBJ_FLAG_SCROLLABLE);         /// Flags
    lv_obj_set_style_bg_color(ui_btn_settings3, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_settings3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_settings3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_settings3, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn_settings3, lv_color_hex(0xA0A0C0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn_settings3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_settings3, lv_color_hex(0x4A6FA5),
                              LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btn_settings3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lbl_navabar_settings3 = lv_label_create(ui_btn_settings3);
    lv_obj_set_width(ui_lbl_navabar_settings3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbl_navabar_settings3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_lbl_navabar_settings3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_navabar_settings3, "SETTINGS");

    ui_panel_status3 = lv_obj_create(ui_panel_navbar3);
    lv_obj_set_width(ui_panel_status3, 104);
    lv_obj_set_height(ui_panel_status3, 78);
    lv_obj_set_align(ui_panel_status3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panel_status3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_status3, lv_color_hex(0x202439),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_status3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_status3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_panel_status3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "$EF WiFi");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_price_header = lv_obj_create(ui_scr_elpris);
    lv_obj_set_width(ui_panel_price_header, 1024);
    lv_obj_set_height(ui_panel_price_header, 110);
    lv_obj_set_x(ui_panel_price_header, 0);
    lv_obj_set_y(ui_panel_price_header, 78);
    lv_obj_remove_flag(ui_panel_price_header, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_panel_price_header, lv_color_hex(0x252538),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_price_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_price_header, lv_color_hex(0x3A3A52),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_price_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_price_header, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_now = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_now, LV_SIZE_CONTENT);  /// 120
    lv_obj_set_height(ui_lbl_price_now, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_price_now, 30);
    lv_obj_set_y(ui_lbl_price_now, 16);
    lv_label_set_text(ui_lbl_price_now, "Current price");
    lv_obj_set_style_text_color(ui_lbl_price_now, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_now, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_val = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_val, LV_SIZE_CONTENT);  /// 160
    lv_obj_set_height(ui_lbl_price_val, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_lbl_price_val, 30);
    lv_obj_set_y(ui_lbl_price_val, 36);
    lv_label_set_text(ui_lbl_price_val, "0.29");
    lv_obj_set_style_text_color(ui_lbl_price_val, lv_color_hex(0x4CAF50),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_price_val, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_unit = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_unit, LV_SIZE_CONTENT);  /// 80
    lv_obj_set_height(ui_lbl_price_unit, LV_SIZE_CONTENT); /// 22
    lv_obj_set_x(ui_lbl_price_unit, 120);
    lv_obj_set_y(ui_lbl_price_unit, 56);
    lv_label_set_text(ui_lbl_price_unit, "kr/kWh");
    lv_obj_set_style_text_color(ui_lbl_price_unit, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_hi = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_hi, LV_SIZE_CONTENT);  /// 280
    lv_obj_set_height(ui_lbl_price_hi, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_price_hi, 400);
    lv_obj_set_y(ui_lbl_price_hi, 16);
    lv_label_set_text(ui_lbl_price_hi, "Max  1.05 kr  at 20:00-23:00");
    lv_obj_set_style_text_color(ui_lbl_price_hi, lv_color_hex(0xFF8A65),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_hi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_lo = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_lo, LV_SIZE_CONTENT);  /// 280
    lv_obj_set_height(ui_lbl_price_lo, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_price_lo, 400);
    lv_obj_set_y(ui_lbl_price_lo, 36);
    lv_label_set_text(ui_lbl_price_lo, "Min  0.05 kr  at 16:00-17:00");
    lv_obj_set_style_text_color(ui_lbl_price_lo, lv_color_hex(0x64B5F6),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_lo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_price_avg = lv_label_create(ui_panel_price_header);
    lv_obj_set_width(ui_lbl_price_avg, LV_SIZE_CONTENT);  /// 280
    lv_obj_set_height(ui_lbl_price_avg, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_lbl_price_avg, 400);
    lv_obj_set_y(ui_lbl_price_avg, 56);
    lv_label_set_text(ui_lbl_price_avg, "Avg  0.35 kr");
    lv_obj_set_style_text_color(ui_lbl_price_avg, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_price_avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_chart = lv_obj_create(ui_scr_elpris);
    lv_obj_set_width(ui_panel_chart, 1024);
    lv_obj_set_height(ui_panel_chart, 412);
    lv_obj_set_x(ui_panel_chart, 0);
    lv_obj_set_y(ui_panel_chart, 188);
    lv_obj_remove_flag(ui_panel_chart, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_left(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_panel_chart, lv_color_hex(0x252535),
                              LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_chart, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_chart, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_chart_elpris = lv_chart_create(ui_panel_chart);
    lv_obj_set_width(ui_chart_elpris, 1000);
    lv_obj_set_height(ui_chart_elpris, 392);
    lv_obj_set_x(ui_chart_elpris, 10);
    lv_obj_set_y(ui_chart_elpris, 10);
    lv_obj_add_flag(
        ui_chart_elpris,
        LV_OBJ_FLAG_OVERFLOW_VISIBLE); // make scales visible - Should it be forced to True?
    // lv_obj_remove_flag( ui_chart_elpris, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 -
    // Shouldn't it be forced to False?
    lv_chart_set_type(ui_chart_elpris, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_chart_elpris, 24);
    lv_chart_set_div_line_count(ui_chart_elpris, 23, 5);
    lv_obj_set_style_bg_color(ui_chart_elpris, lv_color_hex(0x252535),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_elpris, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_chart_elpris, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_elpris_Xaxis = lv_scale_create(ui_chart_elpris);
    lv_scale_set_mode(ui_chart_elpris_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_chart_elpris_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_chart_elpris_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_chart_elpris_Xaxis,
                 50 + lv_obj_get_style_pad_bottom(ui_chart_elpris, LV_PART_MAIN) +
                     lv_obj_get_style_border_width(ui_chart_elpris, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_chart_elpris_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_elpris_Xaxis, 1,
                                LV_PART_ITEMS); // LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chart_elpris_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_elpris_Xaxis, 5, LV_PART_ITEMS);      // minor tick length
    lv_obj_set_style_length(ui_chart_elpris_Xaxis, 10, LV_PART_INDICATOR); // major tick length
    lv_scale_set_range(ui_chart_elpris_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chart_elpris_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chart_elpris_Xaxis, 2 >= 1 ? 2 : 1);
    ui_chart_elpris_Yaxis1 = lv_scale_create(ui_chart_elpris);
    lv_scale_set_mode(ui_chart_elpris_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_chart_elpris_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_chart_elpris_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_chart_elpris_Yaxis1,
                 -50 - lv_obj_get_style_pad_left(ui_chart_elpris, LV_PART_MAIN) -
                     lv_obj_get_style_border_width(ui_chart_elpris, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_elpris_Yaxis1, 5, LV_PART_ITEMS);      // minor tick length
    lv_obj_set_style_length(ui_chart_elpris_Yaxis1, 10, LV_PART_INDICATOR); // major tick length
    lv_scale_set_total_tick_count(ui_chart_elpris_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chart_elpris_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_chart_elpris_Yaxis2 = lv_scale_create(ui_chart_elpris);
    lv_scale_set_mode(ui_chart_elpris_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_chart_elpris_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_chart_elpris_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_chart_elpris_Yaxis2,
                 25 + lv_obj_get_style_pad_right(ui_chart_elpris, LV_PART_MAIN) +
                     lv_obj_get_style_border_width(ui_chart_elpris, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chart_elpris_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_elpris_Yaxis2, 5, LV_PART_ITEMS);      // minor tick length
    lv_obj_set_style_length(ui_chart_elpris_Yaxis2, 10, LV_PART_INDICATOR); // major tick length
    lv_scale_set_total_tick_count(ui_chart_elpris_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chart_elpris_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t* ui_chart_elpris_series_1 =
        lv_chart_add_series(ui_chart_elpris, lv_color_hex(0x4CAF50), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chart_elpris_series_1_array[] = {
        8, 7, 7, 6, 6, 8, 18, 35, 52, 58, 55, 50, 42, 38, 29, 12, 5, 18, 45, 72, 100, 95, 80, 60};
    lv_chart_set_ext_y_array(ui_chart_elpris, ui_chart_elpris_series_1,
                             ui_chart_elpris_series_1_array);

    // This workaround (an invisible outline) is needed because without it chart overflow-visible
    // doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(
        ui_chart_elpris, LV_MAX3(50, 50, 25),
        LV_PART_MAIN | LV_STATE_DEFAULT); // workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_chart_elpris, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_lbl_leg_cheap = lv_label_create(ui_panel_chart);
    lv_obj_set_width(ui_lbl_leg_cheap, LV_SIZE_CONTENT);  /// 60
    lv_obj_set_height(ui_lbl_leg_cheap, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_leg_cheap, 680);
    lv_obj_set_y(ui_lbl_leg_cheap, 8);
    lv_label_set_text(ui_lbl_leg_cheap, "Cheap");
    lv_obj_set_style_text_color(ui_lbl_leg_cheap, lv_color_hex(0x4CAF50),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_leg_cheap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_leg_avg = lv_label_create(ui_panel_chart);
    lv_obj_set_width(ui_lbl_leg_avg, LV_SIZE_CONTENT);  /// 70
    lv_obj_set_height(ui_lbl_leg_avg, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_leg_avg, 750);
    lv_obj_set_y(ui_lbl_leg_avg, 8);
    lv_label_set_text(ui_lbl_leg_avg, "Average");
    lv_obj_set_style_text_color(ui_lbl_leg_avg, lv_color_hex(0x8888AA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_leg_avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_leg_exp = lv_label_create(ui_panel_chart);
    lv_obj_set_width(ui_lbl_leg_exp, LV_SIZE_CONTENT);  /// 80
    lv_obj_set_height(ui_lbl_leg_exp, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_leg_exp, 828);
    lv_obj_set_y(ui_lbl_leg_exp, 8);
    lv_label_set_text(ui_lbl_leg_exp, "Expencive");
    lv_obj_set_style_text_color(ui_lbl_leg_exp, lv_color_hex(0xFF8A65),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_leg_exp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_leg_now = lv_label_create(ui_panel_chart);
    lv_obj_set_width(ui_lbl_leg_now, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_height(ui_lbl_leg_now, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_lbl_leg_now, 918);
    lv_obj_set_y(ui_lbl_leg_now, 8);
    lv_label_set_text(ui_lbl_leg_now, "Now");
    lv_obj_set_style_text_color(ui_lbl_leg_now, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_leg_now, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_scr_elpris         = ui_scr_elpris;
    uic_panel_price_header = ui_panel_price_header;
    uic_lbl_price_now      = ui_lbl_price_now;
    uic_lbl_price_val      = ui_lbl_price_val;
    uic_lbl_price_unit     = ui_lbl_price_unit;
    uic_lbl_price_hi       = ui_lbl_price_hi;
    uic_lbl_price_lo       = ui_lbl_price_lo;
    uic_lbl_price_avg      = ui_lbl_price_avg;
    uic_chart_elpris       = ui_chart_elpris;
    uic_lbl_leg_cheap      = ui_lbl_leg_cheap;
    uic_lbl_leg_exp        = ui_lbl_leg_exp;
}

void ui_scr_elpris_screen_destroy(void) {
    if (ui_scr_elpris)
        lv_obj_del(ui_scr_elpris);

    // NULL screen variables
    uic_scr_elpris           = NULL;
    ui_scr_elpris            = NULL;
    ui_panel_navbar3         = NULL;
    ui_btn_home3             = NULL;
    ui_lbl_navabar_home3     = NULL;
    ui_btn__weather3         = NULL;
    ui_lbl_navabar_weather3  = NULL;
    ui_btn_elpris3           = NULL;
    ui_lbl_navabar_elpris3   = NULL;
    ui_btn_settings3         = NULL;
    ui_lbl_navabar_settings3 = NULL;
    ui_panel_status3         = NULL;
    ui_Label4                = NULL;
    uic_panel_price_header   = NULL;
    ui_panel_price_header    = NULL;
    uic_lbl_price_now        = NULL;
    ui_lbl_price_now         = NULL;
    uic_lbl_price_val        = NULL;
    ui_lbl_price_val         = NULL;
    uic_lbl_price_unit       = NULL;
    ui_lbl_price_unit        = NULL;
    uic_lbl_price_hi         = NULL;
    ui_lbl_price_hi          = NULL;
    uic_lbl_price_lo         = NULL;
    ui_lbl_price_lo          = NULL;
    uic_lbl_price_avg        = NULL;
    ui_lbl_price_avg         = NULL;
    ui_panel_chart           = NULL;
    uic_chart_elpris         = NULL;
    ui_chart_elpris          = NULL;
    uic_lbl_leg_cheap        = NULL;
    ui_lbl_leg_cheap         = NULL;
    ui_lbl_leg_avg           = NULL;
    uic_lbl_leg_exp          = NULL;
    ui_lbl_leg_exp           = NULL;
    ui_lbl_leg_now           = NULL;
}
