// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#ifndef UI_SCR_HOME_H
#define UI_SCR_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_home
extern void ui_scr_home_screen_init(void);
extern void ui_scr_home_screen_destroy(void);
extern lv_obj_t * ui_scr_home;
extern lv_obj_t * ui_TabView;
extern lv_obj_t * ui_tabhome;
extern lv_obj_t * ui_panel_left;
extern lv_obj_t * ui_arc_temp;
extern lv_obj_t * ui_lbl_temp_val;
extern lv_obj_t * ui_lbl_temp_unit;
extern lv_obj_t * ui_arc_pressure;
extern lv_obj_t * ui_lbl_press_val;
extern lv_obj_t * ui_lbl_press_unit;
extern lv_obj_t * ui_arc_humidity;
extern lv_obj_t * ui_lbl_hum_val;
extern lv_obj_t * ui_lbl_hum_unit;
extern lv_obj_t * ui_panel_right;
extern lv_obj_t * ui_panel__current_weather;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_lbl_w_temp;
extern lv_obj_t * ui_lbl_w_temp_hi;
extern lv_obj_t * ui_lbl_w_temp_lo;
extern lv_obj_t * ui_lbl_w_desc;
extern lv_obj_t * ui_lbl_w_loc;
extern lv_obj_t * ui_panel_stat_wind;
extern lv_obj_t * ui_labl_stat_wind_;
extern lv_obj_t * ui_labl_stat_wind_val;
extern lv_obj_t * ui_panel_stat_feels;
extern lv_obj_t * ui_labl_stat_feels;
extern lv_obj_t * ui_labl_stat_feels_val;
extern lv_obj_t * ui_panel_stat_sunrise;
extern lv_obj_t * ui_labl_stat_sunrise;
extern lv_obj_t * ui_lbl_stat_sunrise_val;
extern lv_obj_t * ui_panel_stat_sunset;
extern lv_obj_t * ui_labl_stat_sunset;
extern lv_obj_t * ui_lbl_stat_sunset_val;
extern lv_obj_t * ui_panel_elec_rec;
extern lv_obj_t * ui_lbl_elec_status;
extern lv_obj_t * ui_lbl_elec_sub;
extern lv_obj_t * ui_lbl_elec_price;
extern lv_obj_t * ui_tabweather;
extern lv_obj_t * ui_tabbattery;
extern lv_obj_t * ui_tabelpris;
extern lv_obj_t * ui_tabsettings;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_ta_locationinput;
extern lv_obj_t * ui_dd_price;
extern lv_obj_t * ui_dd_timeout;
extern lv_obj_t * ui_lbl_wifi_name;
extern lv_obj_t * ui_btn_wifi_change;
extern lv_obj_t * ui_dd_timeout;
extern lv_obj_t * ui_panel_statusbar;
extern lv_obj_t * ui_lbl_localtime;
extern lv_obj_t * ui_lbl_wifi_status;

// Traffic light dots (home screen electricity recommendation)
extern lv_obj_t * ui_panel_traffic_light;
extern lv_obj_t * ui_dot_light_green;
extern lv_obj_t * ui_dot_light_amber;
extern lv_obj_t * ui_dot_light_red;

// Hourly strip (home tab "Next Hours" section)
extern lv_obj_t * ui_panel_home_h1;
extern lv_obj_t * ui_lbl_home_htime1;
extern lv_obj_t * ui_lbl_home_htemp1;
extern lv_obj_t * ui_panel_home_h2;
extern lv_obj_t * ui_lbl_home_htime2;
extern lv_obj_t * ui_lbl_home_htemp2;
extern lv_obj_t * ui_panel_home_h3;
extern lv_obj_t * ui_lbl_home_htime3;
extern lv_obj_t * ui_lbl_home_htemp3;
extern lv_obj_t * ui_panel_home_h4;
extern lv_obj_t * ui_lbl_home_htime4;
extern lv_obj_t * ui_lbl_home_htemp4;
extern lv_obj_t * ui_panel_home_h5;
extern lv_obj_t * ui_lbl_home_htime5;
extern lv_obj_t * ui_lbl_home_htemp5;
extern lv_obj_t * ui_panel_home_h6;
extern lv_obj_t * ui_lbl_home_htime6;
extern lv_obj_t * ui_lbl_home_htemp6;

// Battery tab widgets (ui_tab_battery.c)
extern lv_obj_t * ui_panel_batt_hero;
extern lv_obj_t * ui_arc_battery;
extern lv_obj_t * ui_lbl_batt_pct;
extern lv_obj_t * ui_lbl_batt_status;
extern lv_obj_t * ui_panel_batt_stats;
extern lv_obj_t * ui_lbl_batt_voltage;
extern lv_obj_t * ui_lbl_batt_current;
extern lv_obj_t * ui_lbl_batt_cycles;
extern lv_obj_t * ui_panel_batt_trend;
extern lv_obj_t * ui_chart_batt_trend;
extern void ui_tab_battery_init(void);
extern void ui_tab_weather_init(void);
extern void ui_tab_elpris_init(void);
extern void ui_tab_elpris_handle_server_response(const char* json, size_t len);
extern void ui_tab_elpris_update_now(void);
extern void ui_tab_settings_init(void);

// CUSTOM VARIABLES
extern lv_obj_t * uic_scr_home;
extern lv_obj_t * uic_panel_left;
extern lv_obj_t * uic_arc_temp;
extern lv_obj_t * uic_lbl_temp_val;
extern lv_obj_t * uic_arc_pressure;
extern lv_obj_t * uic_lbl_press_unit;
extern lv_obj_t * uic_arc_humidity;
extern lv_obj_t * uic_lbl_hum_val;
extern lv_obj_t * uic_lbl_hum_unit;
extern lv_obj_t * uic_panel_right;
extern lv_obj_t * uic_panel__current_weather;
extern lv_obj_t * uic_lbl_w_temp_hi;
extern lv_obj_t * uic_lbl_w_temp_lo;
extern lv_obj_t * uic_lbl_w_desc;
extern lv_obj_t * uic_lbl_w_loc;
extern lv_obj_t * uic_panel_stat_wind;
extern lv_obj_t * uic_labl_stat_wind_val;
extern lv_obj_t * uic_panel_stat_feels;
extern lv_obj_t * uic_labl_stat_feels;
extern lv_obj_t * uic_labl_stat_feels_val;
extern lv_obj_t * uic_panel_stat_sunrise;
extern lv_obj_t * uic_labl_stat_sunrise;
extern lv_obj_t * uic_lbl_stat_sunrise_val;
extern lv_obj_t * uic_labl_stat_sunset;
extern lv_obj_t * uic_lbl_stat_sunset_val;
extern lv_obj_t * uic_panel_elec_rec;
extern lv_obj_t * uic_lbl_elec_status;
extern lv_obj_t * uic_lbl_elec_sub;
extern lv_obj_t * uic_lbl_elec_price;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
