idf_component_register(
    SRCS
        "ui.c"
        "wifi_popup.c"
        "squareline/ui.c"
        "squareline/ui_helpers.c"
        "squareline/ui_events.c"
        "squareline/ui_themes.c"
        "squareline/ui_theme_manager.c"
        "squareline/components/ui_comp_hook.c"
        "squareline/images/ui_img_sun_behind_cloud_3d_png.c"
        "squareline/images/weather/ui_img_wmo_clear_png.c"
        "squareline/images/weather/ui_img_wmo_mainly_clear_png.c"
        "squareline/images/weather/ui_img_wmo_partly_cloudy_png.c"
        "squareline/images/weather/ui_img_wmo_overcast_png.c"
        "squareline/images/weather/ui_img_wmo_fog_png.c"
        "squareline/images/weather/ui_img_wmo_rime_fog_png.c"
        "squareline/images/weather/ui_img_wmo_drizzle_light_png.c"
        "squareline/images/weather/ui_img_wmo_drizzle_moderate_png.c"
        "squareline/images/weather/ui_img_wmo_drizzle_dense_png.c"
        "squareline/images/weather/ui_img_wmo_freezing_drizzle_light_png.c"
        "squareline/images/weather/ui_img_wmo_freezing_drizzle_dense_png.c"
        "squareline/images/weather/ui_img_wmo_rain_slight_png.c"
        "squareline/images/weather/ui_img_wmo_rain_moderate_png.c"
        "squareline/images/weather/ui_img_wmo_rain_heavy_png.c"
        "squareline/images/weather/ui_img_wmo_freezing_rain_light_png.c"
        "squareline/images/weather/ui_img_wmo_freezing_rain_heavy_png.c"
        "squareline/images/weather/ui_img_wmo_snow_slight_png.c"
        "squareline/images/weather/ui_img_wmo_snow_moderate_png.c"
        "squareline/images/weather/ui_img_wmo_snow_heavy_png.c"
        "squareline/images/weather/ui_img_wmo_snow_grains_png.c"
        "squareline/images/weather/ui_img_wmo_rain_showers_slight_png.c"
        "squareline/images/weather/ui_img_wmo_rain_showers_moderate_png.c"
        "squareline/images/weather/ui_img_wmo_rain_showers_violent_png.c"
        "squareline/images/weather/ui_img_wmo_snow_showers_slight_png.c"
        "squareline/images/weather/ui_img_wmo_snow_showers_heavy_png.c"
        "squareline/images/weather/ui_img_wmo_thunderstorm_png.c"
        "squareline/images/weather/ui_img_wmo_thunderstorm_hail_slight_png.c"
        "squareline/images/weather/ui_img_wmo_thunderstorm_hail_heavy_png.c"
        "squareline/images/weather/ui_img_wx_sunny_png.c"
        "squareline/images/weather/ui_img_wx_partly_png.c"
        "squareline/images/weather/ui_img_wx_cloudy_png.c"
        "squareline/images/weather/ui_img_wx_rain_png.c"
        "squareline/images/weather/ui_img_wx_snow_png.c"
        "squareline/screens/ui_scr_home.c"
        "squareline/screens/ui_tab_battery.c"
        "squareline/screens/ui_tab_weather.c"
        "squareline/screens/ui_tab_elpris.c"
        "squareline/screens/ui_tab_settings.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        display
        screen_timeout
        lvgl__lvgl
)
