#include "kb_swedish.h"

/* Shorthand: regular key with popover, given proportional width */
#define KBN(w) (LV_BUTTONMATRIX_CTRL_POPOVER | (w))

static const char* const KB_MAP_LC_SE[] = {"1#",
                                           "q",
                                           "w",
                                           "e",
                                           "r",
                                           "t",
                                           "y",
                                           "u",
                                           "i",
                                           "o",
                                           "p",
                                           "å",
                                           LV_SYMBOL_BACKSPACE,
                                           "\n",
                                           "ABC",
                                           "a",
                                           "s",
                                           "d",
                                           "f",
                                           "g",
                                           "h",
                                           "j",
                                           "k",
                                           "l",
                                           "ö",
                                           "ä",
                                           LV_SYMBOL_NEW_LINE,
                                           "\n",
                                           "_",
                                           "-",
                                           "z",
                                           "x",
                                           "c",
                                           "v",
                                           "b",
                                           "n",
                                           "m",
                                           ".",
                                           ",",
                                           ":",
                                           "\n",
                                           LV_SYMBOL_LEFT,
                                           " ",
                                           LV_SYMBOL_RIGHT,
                                           LV_SYMBOL_OK,
                                           ""};

static const lv_buttonmatrix_ctrl_t kb_ctrl_lc_se[] = {LV_KEYBOARD_CTRL_BUTTON_FLAGS | 5,
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       KBN(4),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | 7,

                                                       LV_KEYBOARD_CTRL_BUTTON_FLAGS | 6,
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       KBN(3),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | 7,

                                                       LV_BUTTONMATRIX_CTRL_CHECKED | KBN(1),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       KBN(1),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | KBN(1),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | KBN(1),
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | KBN(1),

                                                       LV_BUTTONMATRIX_CTRL_CHECKED | 2,
                                                       6,
                                                       LV_BUTTONMATRIX_CTRL_CHECKED | 2,
                                                       LV_KEYBOARD_CTRL_BUTTON_FLAGS | 2};

static const char* const KB_MAP_UC_SE[] = {"1#",
                                           "Q",
                                           "W",
                                           "E",
                                           "R",
                                           "T",
                                           "Y",
                                           "U",
                                           "I",
                                           "O",
                                           "P",
                                           "Å",
                                           LV_SYMBOL_BACKSPACE,
                                           "\n",
                                           "abc",
                                           "A",
                                           "S",
                                           "D",
                                           "F",
                                           "G",
                                           "H",
                                           "J",
                                           "K",
                                           "L",
                                           "Ö",
                                           "Ä",
                                           LV_SYMBOL_NEW_LINE,
                                           "\n",
                                           "_",
                                           "-",
                                           "Z",
                                           "X",
                                           "C",
                                           "V",
                                           "B",
                                           "N",
                                           "M",
                                           ".",
                                           ",",
                                           ":",
                                           "\n",
                                           LV_SYMBOL_LEFT,
                                           " ",
                                           LV_SYMBOL_RIGHT,
                                           LV_SYMBOL_OK,
                                           ""};

/* Upper ctrl map is identical to lower */
#define kb_ctrl_uc_se kb_ctrl_lc_se

/* ── Public API ── */

void kb_apply_swedish(lv_obj_t* kb) {
    lv_keyboard_set_map(kb, LV_KEYBOARD_MODE_TEXT_LOWER, KB_MAP_LC_SE, kb_ctrl_lc_se);
    lv_keyboard_set_map(kb, LV_KEYBOARD_MODE_TEXT_UPPER, KB_MAP_UC_SE, kb_ctrl_uc_se);
    lv_obj_set_style_text_font(kb, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_t* ta = lv_keyboard_get_textarea(kb);
    if (ta) {
        lv_obj_set_style_text_font(ta, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
