// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: just-GUI

#include "ui.h"

void show_keyboard(lv_event_t* e) {
    lv_obj_remove_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    lv_keyboard_set_textarea(ui_Keyboard1, lv_event_get_target_obj(e));
}

void hide_keyboard(lv_event_t* e) { lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN); }
