#!/usr/bin/env python3
"""
scrub_compile_commands.py

Reads  build/compile_commands.json  (generated by idf.py reconfigure),
expands any @response-file tokens, strips every flag unknown to clang,
injects the Xtensa newlib sysroot include paths, keeps only entries for
YOUR source files, and writes the result to build/lint/compile_commands.json.

The key insight: we must define newlib/GCC internals that Clang doesn't know
about as proper C types/values — NOT as token-paste macros that create circular
references.  We also block the host glibc sysroot from leaking in.

Usage (called by `make lint`):
    python3 scripts/scrub_compile_commands.py \
        --input  build/compile_commands.json          \
        --output build/lint/compile_commands.json     \
        --roots  main components
"""

import argparse
import json
import shlex
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Flags that clang simply does not understand (Xtensa / GCC-specific)
# ---------------------------------------------------------------------------
STRIP_EXACT: set[str] = {
    "-mlongcalls",
    "-mtext-section-literals",
    "-mfix-esp32-psram-cache-issue",
    "-mfix-esp32-psram-cache-strategy=memw",
    "-mdisable-hardware-atomics",
    "-mno-disable-hardware-atomics",
    "-fno-malloc-dce",
    "-fno-tree-switch-conversion",
    "-fstrict-volatile-bitfields",
    "-fzero-init-padding-bits=all",
    "-fno-shrink-wrap",
    "-fno-ipa-sra",
    "-fno-reorder-blocks",
    "-fno-caller-saves",
    "-fconserve-stack",
    "-fstack-reuse=all",
    "-fno-jump-tables",
    "-fno-inline-functions",
    "-fno-inline-functions-called-once",
    "-fno-inline-small-functions",
    "-fno-stack-protector",
    "-fuse-cxa-atexit",
    "-fno-exceptions",
    "-specs=picolibc.specs",
    "-specs=nano.specs",
    "-specs=nosys.specs",
    # GCC-specific warnings that clang rejects
    "-Wno-old-style-declaration",
    "-Wno-frame-address",
    "-Wno-clobbered",
    "-Wno-array-parameter",
    "-Wno-unterminated-string-initialization",
    "-Wno-unused-const-variable",
    "-Wno-strict-aliasing",
    "-Wno-type-limits",
    "-Wno-address",
    "-Wno-write-strings",
    "-Wwrite-strings",
    "-Wlogical-op",
    "-Wformat-overflow=2",
    "-Wformat-truncation",
    "-Wformat-signedness",
    "-Wmissing-declarations",
    "-Wmissing-prototypes",
    "-Wshadow",
    "-Wvla",
}

STRIP_PREFIXES: tuple[str, ...] = (
    "-mfix-esp32",
    "-mabi=",
    "--param",
    "-specs=",
)


def find_xtensa_sysroot() -> tuple[list[str], Path | None]:
    """
    Return (-isystem flags, sysroot_root) for the newest Xtensa toolchain found.
    sysroot_root is the .../xtensa-esp-elf/xtensa-esp-elf directory that contains
    both sys-include/ and include/.
    """
    espressif = Path.home() / ".espressif" / "tools" / "xtensa-esp-elf"
    if not espressif.exists():
        print(f"  [WARN] Xtensa toolchain not found at {espressif}", file=sys.stderr)
        return [], None

    versions = sorted(espressif.iterdir(), reverse=True)
    for ver in versions:
        inner      = ver / "xtensa-esp-elf" / "xtensa-esp-elf"
        sys_inc    = inner / "sys-include"
        inc        = inner / "include"
        if sys_inc.exists() and inc.exists():
            print(f"  [INFO] Using Xtensa sysroot: {ver.name}", file=sys.stderr)
            flags = ["-isystem", str(sys_inc), "-isystem", str(inc)]
            return flags, inner

    print("  [WARN] Could not find xtensa-esp-elf sys-include", file=sys.stderr)
    return [], None


def expand_response_file(token: str, cwd: Path) -> list[str]:
    path_str = token[1:].strip('"').strip("'")
    rsp = Path(path_str)
    if not rsp.is_absolute():
        rsp = cwd / rsp
    try:
        return shlex.split(rsp.read_text())
    except Exception as exc:
        print(f"  [WARN] Could not expand response file {rsp}: {exc}", file=sys.stderr)
        return []


def scrub_tokens(tokens: list[str], cwd: Path) -> list[str]:
    # 1. Expand @response-files
    expanded: list[str] = []
    for tok in tokens:
        if tok.startswith("@"):
            expanded.extend(expand_response_file(tok, cwd))
        else:
            expanded.append(tok)

    # 2. Strip unknown / problematic flags
    result: list[str] = []
    skip_next = False
    for i, tok in enumerate(expanded):
        if skip_next:
            skip_next = False
            continue
        if tok in STRIP_EXACT:
            continue
        matched = False
        for prefix in STRIP_PREFIXES:
            if tok.startswith(prefix):
                # Some two-token flags: "-specs nano.specs"
                if "=" not in tok:
                    next_tok = expanded[i + 1] if i + 1 < len(expanded) else ""
                    if next_tok and not next_tok.startswith("-"):
                        skip_next = True
                matched = True
                break
        if matched:
            continue

        # 3. Strip -isystem / -I paths that point into the host glibc/nix sysroot
        #    so they don't shadow the Xtensa newlib headers.
        if tok in ("-isystem", "-I", "-idirafter", "-iprefix"):
            next_tok = expanded[i + 1] if i + 1 < len(expanded) else ""
            if _is_host_sysroot_path(next_tok):
                skip_next = True
                continue
        if tok.startswith(("-isystem", "-I", "-idirafter")) and "=" not in tok:
            # combined form: "-isystem/nix/store/..."
            for flag in ("-isystem", "-I", "-idirafter"):
                if tok.startswith(flag) and len(tok) > len(flag):
                    path_part = tok[len(flag):]
                    if _is_host_sysroot_path(path_part):
                        matched = True
                        break
            if matched:
                continue

        result.append(tok)

    return result


def _is_host_sysroot_path(path: str) -> bool:
    """
    True for include paths we never want clang to search when targeting Xtensa.

    The tricky case on NixOS: ESP-IDF itself lives under /nix/store/ too, so we
    cannot blanket-ban that prefix.  Instead we look for substrings that only
    appear in host compiler/libc packages, never in ESP-IDF or Xtensa packages.
    """
    # Straightforward host paths on non-Nix systems
    HOST_PREFIXES = (
        "/usr/include",
        "/usr/local/include",
        "/usr/lib/gcc",
    )
    if any(path.startswith(p) for p in HOST_PREFIXES):
        return True

    # On NixOS, host glibc / gcc-lib packages contain these substrings;
    # ESP-IDF / Xtensa / LVGL packages do not.
    HOST_NIX_MARKERS = (
        "-glibc-",
        "-gcc-lib-",
        "-binutils-",
        "-linux-headers-",
        "-libgcc-",
    )
    if "/nix/store/" in path:
        return any(m in path for m in HOST_NIX_MARKERS)

    return False


def build_compat_flags(sysroot_root: Path | None) -> list[str]:
    """
    Return -D flags that teach Clang about newlib/GCC internals it doesn't
    natively understand.

    Rules:
      • __FILE must become a real struct type alias, not a macro, so we
        forward-declare struct __sFILE and typedef it.  We do this via a
        forced-include (-include) rather than -D so we can use real C syntax.
      • _REENT_STDIN/STDOUT/STDERR must expand to their FILE* fields without
        creating circular references.  The reentrant struct _reent has
        _stdin/_stdout/_stderr members; we replicate that minimally.
      • __extension__ and __attribute__ are already known to Clang — defining
        them away often breaks things more than it helps, so we leave them.
      • _REENT (the global reentrancy pointer) is used as a macro argument;
        define it as 0 so the expression is still syntactically valid even
        though it will never be evaluated by clang-tidy's static analysis.
    """
    flags: list[str] = [
        # Tell Clang we're cross-compiling for a bare-metal Xtensa target so it
        # doesn't pull in host POSIX/glibc assumptions.
        "--target=xtensa",

        # Suppress errors for unknown GCC attributes / pragmas that appear in
        # ESP-IDF and newlib headers.
        "-Wno-unknown-attributes",
        "-Wno-unknown-pragmas",
        "-Wno-ignored-attributes",

        # newlib uses __asm__ syntax Clang tolerates but may warn on.
        "-Wno-gnu-statement-expression",

        # The _REENT macro is passed as an argument to _REENT_STDIN etc.
        # Defining it as ((struct _reent *)0) keeps the type correct and
        # prevents "undeclared identifier" errors in macro expansions.
        "-D_REENT=((struct _reent *)0)",

        # _REENT_STDIN(r) etc. expand to the FILE* fields on the reent struct.
        # We define them to NULL casts so they're valid C without being circular.
        "-D_REENT_STDIN(r)=((FILE *)0)",
        "-D_REENT_STDOUT(r)=((FILE *)0)",
        "-D_REENT_STDERR(r)=((FILE *)0)",

        # newlib's stdio.h tests for __FILE being defined before typedef-ing FILE.
        # We supply it as a forward declaration alias for __sFILE (the real struct).
        # Using -D means "pretend this identifier is already #defined", which
        # prevents the typedef line from firing — but that requires FILE to exist
        # already, which it won't.  Better to let the typedef happen and just
        # pre-define __FILE as __sFILE so the typedef resolves.
        "-D__FILE=__sFILE",

        # picolibc / newlib uses __HAVE_LOCALE_INFO__ gating
        "-D__HAVE_LOCALE_INFO__=0",

        # glibc feature-test macro that leaks in via nix; must be a function-like
        # macro returning 0 so "#if __GLIBC_USE(X)" doesn't error.
        "-D__GLIBC_USE(x)=0",

        # Suppress the cascade of errors that come from the broken ../hal.h
        # relative include inside the nix Xtensa package.
        "-Wno-error",
    ]

    return flags


def scrub_entry(
    entry: dict,
    cwd: Path,
    extra_isystem: list[str],
    compat_flags: list[str],
) -> dict:
    entry = dict(entry)
    tokens = shlex.split(entry["command"])
    tokens = scrub_tokens(tokens, cwd)

    if extra_isystem or compat_flags:
        # Insert right after the compiler binary (tokens[0])
        tokens = [tokens[0]] + compat_flags + extra_isystem + tokens[1:]

    entry["command"] = " ".join(shlex.quote(t) for t in tokens)
    return entry


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default="build/compile_commands.json")
    parser.add_argument("--output", default="build/lint/compile_commands.json")
    parser.add_argument("--roots",  nargs="+", default=["main", "components"])
    args = parser.parse_args()

    input_path  = Path(args.input).resolve()
    output_path = Path(args.output)

    if not input_path.exists():
        print(
            f"[ERROR] {input_path} not found. Run 'idf.py reconfigure' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    with input_path.open() as f:
        db = json.load(f)

    project_root      = input_path.parent.parent
    abs_roots         = [str(project_root / r) for r in args.roots]
    extra_isystem, sysroot_root = find_xtensa_sysroot()
    compat_flags      = build_compat_flags(sysroot_root)

    kept, dropped = [], 0
    for entry in db:
        file_path = entry.get("file", "")
        if not any(file_path.startswith(r + "/") for r in abs_roots):
            dropped += 1
            continue
        if "managed_components" in file_path:
            dropped += 1
            continue
        cwd = Path(entry.get("directory", str(project_root)))
        kept.append(scrub_entry(entry, cwd, extra_isystem, compat_flags))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        json.dump(kept, f, indent=2)

    print(f"[OK] {output_path}: {len(kept)} entries kept, {dropped} dropped")


if __name__ == "__main__":
    main()
