#!/usr/bin/env python3
"""
scrub_compile_commands.py

Reads  build/compile_commands.json  (generated by idf.py reconfigure),
expands any @response-file tokens, strips every flag unknown to clang,
injects the Xtensa newlib/picolibc sysroot include paths so clang can
find system headers like <machine/endian.h>, keeps only entries for YOUR
source files, and writes the result to build/lint/compile_commands.json.

run-clang-tidy -p build/lint  picks up the clean DB automatically.

Usage (called by `make lint`):
    python3 scripts/scrub_compile_commands.py \
        --input  build/compile_commands.json          \
        --output build/lint/compile_commands.json     \
        --roots  main components
"""

import argparse
import json
import shlex
import sys
from pathlib import Path

STRIP_EXACT: set[str] = {
    "-mlongcalls",
    "-mtext-section-literals",
    "-mfix-esp32-psram-cache-issue",
    "-mfix-esp32-psram-cache-strategy=memw",
    "-mdisable-hardware-atomics",
    "-mno-disable-hardware-atomics",
    "-fno-malloc-dce",
    "-fno-tree-switch-conversion",
    "-fstrict-volatile-bitfields",
    "-fzero-init-padding-bits=all",
    "-fno-shrink-wrap",
    "-fno-ipa-sra",
    "-fno-reorder-blocks",
    "-fno-caller-saves",
    "-fconserve-stack",
    "-fstack-reuse=all",
    "-fno-jump-tables",
    "-fno-inline-functions",
    "-fno-inline-functions-called-once",
    "-fno-inline-small-functions",
    "-fno-stack-protector",
    "-fuse-cxa-atexit",
    "-fno-exceptions",
    "-specs=picolibc.specs",
    "-specs=nano.specs",
    "-specs=nosys.specs",
    "-Wno-old-style-declaration",
    "-Wno-frame-address",
    "-Wno-clobbered",
    "-Wno-array-parameter",
    "-Wno-unterminated-string-initialization",
    "-Wno-unused-const-variable",
    "-Wno-strict-aliasing",
    "-Wno-type-limits",
    "-Wno-address",
    "-Wno-write-strings",
    "-Wwrite-strings",
    "-Wlogical-op",
    "-Wformat-overflow=2",
    "-Wformat-truncation",
    "-Wformat-signedness",
    "-Wmissing-declarations",
    "-Wmissing-prototypes",
    "-Wshadow",
    "-Wvla",
}

STRIP_PREFIXES: tuple[str, ...] = (
    "-mfix-esp32",
    "-mabi=",
    "--param",
    "-specs=",
)


def find_xtensa_sysroot() -> list[str]:
    espressif = Path.home() / ".espressif" / "tools" / "xtensa-esp-elf"
    if not espressif.exists():
        print(f"  [WARN] Xtensa toolchain not found at {espressif}", file=sys.stderr)
        return []
    versions = sorted(espressif.iterdir(), reverse=True)
    for ver in versions:
        sys_include = ver / "xtensa-esp-elf" / "xtensa-esp-elf" / "sys-include"
        include     = ver / "xtensa-esp-elf" / "xtensa-esp-elf" / "include"
        if sys_include.exists() and include.exists():
            print(f"  [INFO] Using Xtensa sysroot: {ver.name}", file=sys.stderr)
            return ["-isystem", str(sys_include), "-isystem", str(include)]
    print("  [WARN] Could not find xtensa-esp-elf sys-include", file=sys.stderr)
    return []


def expand_response_file(token: str, cwd: Path) -> list[str]:
    path_str = token[1:].strip('"').strip("'")
    rsp = Path(path_str)
    if not rsp.is_absolute():
        rsp = cwd / rsp
    try:
        return shlex.split(rsp.read_text())
    except Exception as exc:
        print(f"  [WARN] Could not expand response file {rsp}: {exc}", file=sys.stderr)
        return []


def scrub_tokens(tokens: list[str], cwd: Path) -> list[str]:
    expanded: list[str] = []
    for tok in tokens:
        if tok.startswith("@"):
            expanded.extend(expand_response_file(tok, cwd))
        else:
            expanded.append(tok)

    result: list[str] = []
    skip_next = False
    for i, tok in enumerate(expanded):
        if skip_next:
            skip_next = False
            continue
        if tok in STRIP_EXACT:
            continue
        matched = False
        for prefix in STRIP_PREFIXES:
            if tok.startswith(prefix):
                if "=" not in tok:
                    next_tok = expanded[i + 1] if i + 1 < len(expanded) else ""
                    if next_tok and not next_tok.startswith("-"):
                        skip_next = True
                matched = True
                break
        if matched:
            continue
        result.append(tok)
    return result


def scrub_entry(entry: dict, cwd: Path, extra_isystem: list[str]) -> dict:
    entry = dict(entry)
    tokens = shlex.split(entry["command"])
    tokens = scrub_tokens(tokens, cwd)
    if extra_isystem:
        tokens = [tokens[0]] + extra_isystem + tokens[1:]
    entry["command"] = " ".join(shlex.quote(t) for t in tokens)
    return entry


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default="build/compile_commands.json")
    parser.add_argument("--output", default="build/lint/compile_commands.json")
    parser.add_argument("--roots",  nargs="+", default=["main", "components"])
    args = parser.parse_args()

    input_path  = Path(args.input).resolve()
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"[ERROR] {input_path} not found. Run 'idf.py reconfigure' first.",
              file=sys.stderr)
        sys.exit(1)

    with input_path.open() as f:
        db = json.load(f)

    project_root  = input_path.parent.parent
    abs_roots     = [str(project_root / r) for r in args.roots]
    extra_isystem = find_xtensa_sysroot()

    kept, dropped = [], 0
    for entry in db:
        file_path = entry.get("file", "")
        if not any(file_path.startswith(r + "/") for r in abs_roots):
            dropped += 1
            continue
        if "managed_components" in file_path:
            dropped += 1
            continue
        cwd = Path(entry.get("directory", str(project_root)))
        kept.append(scrub_entry(entry, cwd, extra_isystem))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        json.dump(kept, f, indent=2)

    print(f"[OK] {output_path}: {len(kept)} entries kept, {dropped} dropped")


if __name__ == "__main__":
    main()
