name: Format

on:
  push:
    branches: ["**"]
    paths-ignore:
          - "**.md"
          - ".gitignore"
          - "LICENSE"
          - "docs/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
          - "**.md"
          - ".gitignore"
          - "LICENSE"
          - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends clang-format

      - name: Check formatting
        run: make format-ci
