name: Format

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Check Formatting
        run: |
          nix develop . --command bash -c "make format-ci"
