name: Lint

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: clang-tidy
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Cache Espressif Toolchains
        id: cache-espressif-tools
        uses: actions/cache@v4
        with:
          path: /home/runner/.espressif
          key: espressif-tools-${{ hashFiles('flake.lock') }}

      - name: Prepare and Run Linter
        run: |
          nix develop . --command bash -c "idf.py reconfigure && make lint-ci"

      - name: Upload lint DB on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-db-${{ github.sha }}
          path: build/lint/compile_commands.json
          retention-days: 7
